### ISSUE TITLE
more errors for indexer v2.9.1

### ISSUE THREAD

**Issue by TurtleSnail** [AcalaNetwork/bodhi.js#1048]
```
Nov 08 15:37:01 ct12 yarn[3192213]: 2024-11-08 15:37:01             VEC: Unable to decode on index 2 createType(ExtrinsicV4):: createType(Call):: findMetaCall: Unable to find Call with index [0, 70]/[0,70]
Nov 08 15:37:01 ct12 yarn[3192213]: 2024-11-08 15:37:01        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: findMetaCall: Unable to find Call with index [0, 70]/[0,70]
Nov 08 15:37:01 ct12 yarn[3192213]: 2024-11-08T15:37:01.215Z <fetch> ERROR failed to fetch Block hash="0xc883dbf7d444e0ca3224bdfc1f06125d8e8d1cb27c86f6b722af26d03da8f330" height="7983812"
Nov 08 15:37:01 ct12 yarn[3192213]: 2024-11-08T15:37:01.215Z <api> ERROR Maximum number of retries reached
Nov 08 15:37:01 ct12 yarn[3192213]: 2024-11-08T15:37:01.215Z <BlockDispatcherService> ERROR Failed to fetch block 7983812.
Nov 08 15:37:01 ct12 yarn[3192213]: Error: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: findMetaCall: Unable to find Call with index [0, 70]/[0,70]
Nov 08 15:37:01 ct12 yarn[3192213]:     at ApiPromiseConnection.handleError (/home/karura/.nvm/versions/node/v20.18.0/lib/node_modules/@subql/node/dist/indexer/apiPromise.connection.js:82:31)
Nov 08 15:37:01 ct12 yarn[3192213]:     at /home/karura/.nvm/versions/node/v20.18.0/lib/node_modules/@subql/node/dist/utils/substrate.js:173:60
Nov 08 15:37:01 ct12 yarn[3192213]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Nov 08 15:37:01 ct12 yarn[3192213]:     at async getBlockByHeight (/home/karura/.nvm/versions/node/v20.18.0/lib/node_modules/@subql/node/dist/utils/substrate.js:171:19)
Nov 08 15:37:01 ct12 yarn[3192213]:     at async Promise.all (index 0)
Nov 08 15:37:01 ct12 yarn[3192213]:     at async fetchBlocksBatches (/home/karura/.nvm/versions/node/v20.18.0/lib/node_modules/@subql/node/dist/utils/substrate.js:225:20)
Nov 08 15:37:01 ct12 yarn[3192213]:     at async ApiPromiseConnection.fetchBlocks (/home/karura/.nvm/versions/node/v20.18.0/lib/node_modules/@subql/node/dist/indexer/apiPromise.connection.js:48:24)
Nov 08 15:37:01 ct12 yarn[3192213]:     at async Proxy.<anonymous> (/home/karura/.nvm/versions/node/v20.18.0/lib/node_modules/@subql/node/node_modules/@subql/node-core/dist/indexer/connectionPool.service.js:88:44)
Nov 08 15:37:01 ct12 yarn[3192213]:     at async backoffRetryInternal (/home/karura/.nvm/versions/node/v20.18.0/lib/node_modules/@subql/node/node_modules/@subql/node-core/dist/utils/promise.js:44:16)
Nov 08 15:37:01 ct12 yarn[3192213]:     at async ApiService.retryFetch (/home/karura/.nvm/versions/node/v20.18.0/lib/node_modules/@subql/node/node_modules/@subql/node-core/dist/api.service.js:33:20)
Nov 08 15:37:01 ct12 yarn[3192213]: 2024-11-08T15:37:01.216Z <BlockDispatcherService> ERROR Failed to enqueue fetched block to process
Nov 08 15:37:01 ct12 yarn[3192213]: Error: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: findMetaCall: Unable to find Call with index [0, 70]/[0,70]
Nov 08 15:37:01 ct12 yarn[3192213]:     at ApiPromiseConnection.handleError (/home/karura/.nvm/versions/node/v20.18.0/lib/node_modules/@subql/node/dist/indexer/apiPromise.connection.js:82:31)
Nov 08 15:37:01 ct12 yarn[3192213]:     at /home/karura/.nvm/versions/node/v20.18.0/lib/node_modules/@subql/node/dist/utils/substrate.js:173:60
Nov 08 15:37:01 ct12 yarn[3192213]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Nov 08 15:37:01 ct12 yarn[3192213]:     at async getBlockByHeight (/home/karura/.nvm/versions/node/v20.18.0/lib/node_modules/@subql/node/dist/utils/substrate.js:171:19)
Nov 08 15:37:01 ct12 yarn[3192213]:     at async Promise.all (index 0)
Nov 08 15:37:01 ct12 yarn[3192213]:     at async fetchBlocksBatches (/home/karura/.nvm/versions/node/v20.18.0/lib/node_modules/@subql/node/dist/utils/substrate.js:225:20)
Nov 08 15:37:01 ct12 yarn[3192213]:     at async ApiPromiseConnection.fetchBlocks (/home/karura/.nvm/versions/node/v20.18.0/lib/node_modules/@subql/node/dist/indexer/apiPromise.connection.js:48:24)
Nov 08 15:37:01 ct12 yarn[3192213]:     at async Proxy.<anonymous> (/home/karura/.nvm/versions/node/v20.18.0/lib/node_modules/@subql/node/node_modules/@subql/node-core/dist/indexer/connectionPool.service.js:88:44)
Nov 08 15:37:01 ct12 yarn[3192213]:     at async backoffRetryInternal (/home/karura/.nvm/versions/node/v20.18.0/lib/node_modules/@subql/node/node_modules/@subql/node-core/dist/utils/promise.js:44:16)
Nov 08 15:37:01 ct12 yarn[3192213]:     at async ApiService.retryFetch (/home/karura/.nvm/versions/node/v20.18.0/lib/node_modules/@subql/node/node_modules/@subql/node-core/dist/api.service.js:33:20)
Nov 08 15:37:01 ct12 systemd[1]: karura-idx.service: Main process exited, code=exited, status=1/FAILURE
Nov 08 15:37:01 ct12 systemd[1]: karura-idx.service: Failed with result 'exit-code'.
```

**Comment by shunjizhan** [comment]
Hi, can you try laster subql node `5.2.9`? This should work

**Comment by shunjizhan** [comment]
just to clarify, if you are using our subql docker image, it's `acala/evm-subql:2.9.1`, which  [internally use subql node 5.2.9](https://github.com/AcalaNetwork/bodhi.js/blob/master/packages/evm-subql/Dockerfile#L21).

So if you run a subql node directly, use 5.2.9 instead of 2.9.1
