### ISSUE TITLE
eth-rpc-adapter server should restart automatically 

### ISSUE THREAD

**Issue by zjb0807** [AcalaNetwork/bodhi.js#1052]
When `eth-rpc-adapter` exits or runtime is upgraded, the docker will not restart automatically.  But it was working before

**Comment by zjb0807** [comment]
```
{"level":20,"time":1741903588772,"pid":1,"hostname":"e553cb1c05c7","dd":{"trace_id":"5149450522391938828","span_id":"8013625915150131687","service":"eth rpc","version":"2.9.5"},"0":{"id":0,"jsonrpc":"2.0","method":
"eth_getBlockByNumber","params":["latest",false]},"msg":"⬇ request"}
2025-03-13 22:10:00          API-WS: disconnected from wss://karura-internal-rpc.aca-api.network:8443: 1006:: Abnormal Closure
2025-03-13 22:10:00        RPC-CORE: getHeader(hash?: BlockHash): Header:: disconnected from wss://karura-internal-rpc.aca-api.network:8443: 1006:: Abnormal Closure
2025-03-13 22:10:00        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: disconnected from wss://karura-internal-rpc.aca-api.network:8443: 1006:: Abnormal Closure
2025-03-13 22:10:01        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: disconnected from wss://karura-internal-rpc.aca-api.network:8443: 1006:: Abnormal Closure
2025-03-13 22:10:01        RPC-CORE: getHeader(hash?: BlockHash): Header:: disconnected from wss://karura-internal-rpc.aca-api.network:8443: 1006:: Abnormal Closure                                                  2025-03-13 22:10:02        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: disconnected from wss://karura-internal-rpc.aca-api.network:8443: 1006:: Abnormal Closure
2025-03-13 22:10:02        RPC-CORE: getHeader(hash?: BlockHash): Header:: disconnected from wss://karura-internal-rpc.aca-api.network:8443: 1006:: Abnormal Closure                                                  2025-03-13 22:10:03        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: disconnected from wss://karura-internal-rpc.aca-api.network:8443: 1006:: Abnormal Closure
2025-03-13 22:10:03        RPC-CORE: getHeader(hash?: BlockHash): Header:: disconnected from wss://karura-internal-rpc.aca-api.network:8443: 1006:: Abnormal Closure                                                  2025-03-13 22:10:04        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: disconnected from wss://karura-internal-rpc.aca-api.network:8443: 1006:: Abnormal Closure
2025-03-13 22:10:04        RPC-CORE: getHeader(hash?: BlockHash): Header:: disconnected from wss://karura-internal-rpc.aca-api.network:8443: 1006:: Abnormal Closure                                                  _onNewHead task failed, give up 0x205f6949aa3c9e93e27cd207cf672ecf7cac38f6b4921c039210f676217ffa23 Error: disconnected from wss://karura-internal-rpc.aca-api.network:8443: 1006:: Abnormal Closure
2025-03-13 22:10:14        RPC-CORE: getHeader(hash?: BlockHash): Header:: disconnected from wss://karura-internal-rpc.aca-api.network:8443: 1006:: Abnormal Closure                                                  /app/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:360
        const error = new Error(`disconnected from ${this.endpoint}: ${event.code}:: ${event.reason || (0, errors_js_1.getWSErrorString)(event.code)}`);                                                                                    ^
                                                                                                                                                                                                                      Error: disconnected from wss://karura-internal-rpc.aca-api.network:8443: 1006:: Abnormal Closure
    at WebSocket.__internal__onSocketClose (/app/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:360:23)                                                                                                              at callListener (/app/node_modules/@polkadot/x-ws/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onClose (/app/node_modules/@polkadot/x-ws/node_modules/ws/lib/event-target.js:220:9)                                                                                                                     at WebSocket.emit (node:events:517:28)
    at WebSocket.emitClose (/app/node_modules/@polkadot/x-ws/node_modules/ws/lib/websocket.js:272:10)
    at TLSSocket.socketOnClose (/app/node_modules/@polkadot/x-ws/node_modules/ws/lib/websocket.js:1341:15)
    at TLSSocket.emit (node:events:529:35)
    at TLSSocket.emit (/app/node_modules/dd-trace/packages/datadog-instrumentations/src/net.js:61:25)
    at node:net:350:12
    at TCP.done (node:_tls_wrap:657:7)

Node.js v18.20.5
```

It seems that ws is disconnected and node has not exited
