### ISSUE TITLE
only EIP-155 transactions are supported. but get unknown not implemented

### ISSUE THREAD

**Issue by gluneau** [AcalaNetwork/bodhi.js#138]
This was deploying yesterday, not today.  Ideas? 

```
hardhat npx hardhat run scripts/sample-script.js --network development
ProviderError: only EIP-155 transactions are supported. but get unknown not implemented (method="only EIP-155 transactions are supported. but get unknown", provider="eth-providers", code=NOT_IMPLEMENTED, version=bodhi.js/providers/2.1.3)
    at HttpProvider.request (/home/acala/hardhat/node_modules/hardhat/src/internal/core/providers/http.ts:49:19)
    at LocalAccountsProvider.request (/home/acala/hardhat/node_modules/hardhat/src/internal/core/providers/accounts.ts:181:36)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at EthersProviderWrapper.send (/home/acala/hardhat/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20
```

RPC side:
```
[1637703396205] DEBUG (907699 on XPS-15-7590): incoming request
    jsonrpc: "2.0"
    method: "eth_sendRawTransaction"
    params: [
      "0xf90...f2fb"
    ]
    id: 11
[1637703396235] DEBUG (907699 on XPS-15-7590): request completed
    id: 11
    jsonrpc: "2.0"
    error: {
      "code": -32601,
      "message": "only EIP-155 transactions are supported. but get unknown not implemented (method=\"only EIP-155 transactions are supported. but get unknown\", provider=\"eth-providers\", code=NOT_IMPLEMENTED, version=bodhi.js/providers/2.1.3)"
    }

```

Logs in the node, notice `Execution Error(OutOfGas)`?
```
mandala-node_1    | 2021-11-23 21:36:36.182 DEBUG ThreadId(59) evm: Execution logs []    
mandala-node_1    | 2021-11-23 21:36:36.182 DEBUG ThreadId(59) evm: handle_mirrored_token: address: 0x3d3593927228553b349767aba68d4fb1514678cb    
mandala-node_1    | 2021-11-23 21:36:36.182 DEBUG ThreadId(59) evm: handle_mirrored_token: address: 0x000000000000000000636f6e736f6c652e6c6f67    
mandala-node_1    | 2021-11-23 21:36:36.182 DEBUG ThreadId(59) evm: Call execution using address 0x0000…6f67: Succeed(Stopped)    
mandala-node_1    | 2021-11-23 21:36:36.182 DEBUG ThreadId(59) evm: Updating storage for 0x3d3593927228553b349767aba68d4fb1514678cb [index: 0x0000000000000000000000000000000000000000000000000000000000000000, value: 0x48656c6c6f2c204861726468617421000000000000000000000000000000001e]    
mandala-node_1    | 2021-11-23 21:36:36.182 DEBUG ThreadId(59) evm: Create execution using address 0x3d35…78cb: Succeed(Returned)    
mandala-node_1    | 2021-11-23 21:36:36.182 DEBUG ThreadId(59) evm: Inserting code (1851 bytes) at 0x3d3593927228553b349767aba68d4fb1514678cb    
mandala-node_1    | 2021-11-23 21:36:36.182 DEBUG ThreadId(59) evm: Execution Succeed(Returned) [source: 0x75e480db528101a381ce68544611c169ad7eb342, value: 0, gas_limit: 512520, actual_fee: 500239]    
mandala-node_1    | 2021-11-23 21:36:36.182 DEBUG ThreadId(59) evm: Execution logs []    
mandala-node_1    | 2021-11-23 21:36:36.182 DEBUG ThreadId(59) evm: handle_mirrored_token: address: 0x3d3593927228553b349767aba68d4fb1514678cb    
mandala-node_1    | 2021-11-23 21:36:36.182 DEBUG ThreadId(59) evm: handle_mirrored_token: address: 0x000000000000000000636f6e736f6c652e6c6f67    
mandala-node_1    | 2021-11-23 21:36:36.182 DEBUG ThreadId(59) evm: Call execution using address 0x0000…6f67: Succeed(Stopped)    
mandala-node_1    | 2021-11-23 21:36:36.182 DEBUG ThreadId(59) evm: Updating storage for 0x3d3593927228553b349767aba68d4fb1514678cb [index: 0x0000000000000000000000000000000000000000000000000000000000000000, value: 0x48656c6c6f2c204861726468617421000000000000000000000000000000001e]    
mandala-node_1    | 2021-11-23 21:36:36.182 DEBUG ThreadId(59) evm: Create execution using address 0x3d35…78cb: Succeed(Returned)    
mandala-node_1    | 2021-11-23 21:36:36.182 DEBUG ThreadId(59) evm: Execution Error(OutOfGas) [source: 0x75e480db528101a381ce68544611c169ad7eb342, value: 0, gas_limit: 463368, actual_fee: 463368]    
mandala-node_1    | 2021-11-23 21:36:36.182 DEBUG ThreadId(59) evm: Execution logs []    
mandala-node_1    | 2021-11-23 21:36:36.183 DEBUG ThreadId(59) evm: handle_mirrored_token: address: 0x3d3593927228553b349767aba68d4fb1514678cb    
mandala-node_1    | 2021-11-23 21:36:36.183 DEBUG ThreadId(59) evm: handle_mirrored_token: address: 0x000000000000000000636f6e736f6c652e6c6f67    
mandala-node_1    | 2021-11-23 21:36:36.183 DEBUG ThreadId(59) evm: Call execution using address 0x0000…6f67: Succeed(Stopped)    
mandala-node_1    | 2021-11-23 21:36:36.183 DEBUG ThreadId(59) evm: Updating storage for 0x3d3593927228553b349767aba68d4fb1514678cb [index: 0x0000000000000000000000000000000000000000000000000000000000000000, value: 0x48656c6c6f2c204861726468617421000000000000000000000000000000001e]    
mandala-node_1    | 2021-11-23 21:36:36.183 DEBUG ThreadId(59) evm: Create execution using address 0x3d35…78cb: Succeed(Returned)    
mandala-node_1    | 2021-11-23 21:36:36.183 DEBUG ThreadId(59) evm: Execution Error(OutOfGas) [source: 0x75e480db528101a381ce68544611c169ad7eb342, value: 0, gas_limit: 487944, actual_fee: 487944]    
mandala-node_1    | 2021-11-23 21:36:36.183 DEBUG ThreadId(59) evm: Execution logs []    
mandala-node_1    | 2021-11-23 21:36:36.183 DEBUG ThreadId(59) evm: handle_mirrored_token: address: 0x3d3593927228553b349767aba68d4fb1514678cb    
mandala-node_1    | 2021-11-23 21:36:36.183 DEBUG ThreadId(59) evm: handle_mirrored_token: address: 0x000000000000000000636f6e736f6c652e6c6f67    
mandala-node_1    | 2021-11-23 21:36:36.183 DEBUG ThreadId(59) evm: Call execution using address 0x0000…6f67: Succeed(Stopped)    
mandala-node_1    | 2021-11-23 21:36:36.183 DEBUG ThreadId(59) evm: Updating storage for 0x3d3593927228553b349767aba68d4fb1514678cb [index: 0x0000000000000000000000000000000000000000000000000000000000000000, value: 0x48656c6c6f2c204861726468617421000000000000000000000000000000001e]    
mandala-node_1    | 2021-11-23 21:36:36.183 DEBUG ThreadId(59) evm: Create execution using address 0x3d35…78cb: Succeed(Returned)    
mandala-node_1    | 2021-11-23 21:36:36.183 DEBUG ThreadId(59) evm: Inserting code (1851 bytes) at 0x3d3593927228553b349767aba68d4fb1514678cb    
mandala-node_1    | 2021-11-23 21:36:36.183 DEBUG ThreadId(59) evm: Execution Succeed(Returned) [source: 0x75e480db528101a381ce68544611c169ad7eb342, value: 0, gas_limit: 500232, actual_fee: 500047]    
mandala-node_1    | 2021-11-23 21:36:36.183 DEBUG ThreadId(59) evm: Execution logs [] 
```

**Comment by gluneau** [comment]
Same error using truffle:
```
Starting migrations...
======================
> Network name:    'mandala'
> Network id:      595
> Block gas limit: 15000000 (0xe4e1c0)


2_deploy_contracts.js
=====================

   Deploying 'ERC1155User'
   -----------------------------

Error:  *** Deployment Failed ***

"ERC1155User" -- only EIP-155 transactions are supported. but get unknown not implemented (method="only EIP-155 transactions are supported. but get unknown", provider="eth-providers", code=NOT_IMPLEMENTED, version=bodhi.js/providers/2.1.3).

```
