### ISSUE TITLE
scheduler example failure

### ISSUE THREAD

**Issue by shunjizhan** [AcalaNetwork/bodhi.js#150]
```
3 passing (2m)
  2 failing

  1) Schedule
       works with RecurringPayment:
     Error: Timeout of 50000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/shunjizhan/Acala/bodhi.js/examples/scheduler/test/Scheduler.test.ts)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  2) Schedule
       works with Subscription:
     Error: 1014: Priority is too low: (399627509098620 vs 366996901750516): The transaction has too low priority to replace another transaction already in the pool.
      at RpcCoder._checkError (/Users/shunjizhan/Acala/bodhi.js/common/temp/node_modules/.pnpm/@polkadot+rpc-provider@6.9.2/node_modules/@polkadot/rpc-provider/coder/index.cjs:84:13)
      at RpcCoder.decodeResponse (/Users/shunjizhan/Acala/bodhi.js/common/temp/node_modules/.pnpm/@polkadot+rpc-provider@6.9.2/node_modules/@polkadot/rpc-provider/coder/index.cjs:47:10)
      at WsProvider.value (/Users/shunjizhan/Acala/bodhi.js/common/temp/node_modules/.pnpm/@polkadot+rpc-provider@6.9.2/node_modules/@polkadot/rpc-provider/ws/index.cjs:260:90)
      at W3CWebSocket.value [as onmessage] (/Users/shunjizhan/Acala/bodhi.js/common/temp/node_modules/.pnpm/@polkadot+rpc-provider@6.9.2/node_modules/@polkadot/rpc-provider/ws/index.cjs:240:153)
      at W3CWebSocket._dispatchEvent [as dispatchEvent] (/Users/shunjizhan/Acala/bodhi.js/common/temp/node_modules/.pnpm/yaeti@0.0.6/node_modules/yaeti/lib/EventTarget.js:107:17)
      at W3CWebSocket.onMessage (/Users/shunjizhan/Acala/bodhi.js/common/temp/node_modules/.pnpm/websocket@1.0.34/node_modules/websocket/lib/W3CWebSocket.js:234:14)
      at WebSocketConnection.<anonymous> (/Users/shunjizhan/Acala/bodhi.js/common/temp/node_modules/.pnpm/websocket@1.0.34/node_modules/websocket/lib/W3CWebSocket.js:205:19)
      at WebSocketConnection.EventEmitter.emit (domain.js:467:12)
      at WebSocketConnection.processFrame (/Users/shunjizhan/Acala/bodhi.js/common/temp/node_modules/.pnpm/websocket@1.0.34/node_modules/websocket/lib/WebSocketConnection.js:554:26)
      at /Users/shunjizhan/Acala/bodhi.js/common/temp/node_modules/.pnpm/websocket@1.0.34/node_modules/websocket/lib/WebSocketConnection.js:323:40
      at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

**Comment by shunjizhan** [comment]
full logs
<img width="1505" alt="Screen Shot 2021-11-26 at 10 19 24" src="https://user-images.githubusercontent.com/16548786/143517062-55b87efb-45e7-4089-b1f7-c941a40bb409.png">

**Comment by shunjizhan** [comment]
tested again and this actually works with newest version of mandala and bodhi.js
