### ISSUE TITLE
`eth_sendRawTransaction` failed decoding evm.ethCall:: Struct: failed on gas_limit: Negative number passed to unsigned type

### ISSUE THREAD

**Issue by gluneau** [AcalaNetwork/bodhi.js#179]
Error:
```
[1638850393105] DEBUG (1259287 on XPS-15-7590): incoming request
    id: 736679059712725
    jsonrpc: "2.0"
    params: [
      "0xf...44"
    ]
    method: "eth_sendRawTransaction"
[1638850393122] ERROR (1259287 on XPS-15-7590): request error
    methodName: "eth_sendRawTransaction"
    params: [
      "0xf...44"
    ]
    err: {
      "type": "Error",
      "message": "createType(Call):: Call: failed decoding evm.ethCall:: Struct: failed on args: {\"action\":\"{\\\"_enum\\\":{\\\"Call\\\":\\\"H160\\\",\\\"Create\\\":\\\"Null\\\"}}\",\"input\":\"Bytes\",\"value\":\"Compact<u128>\",\"gas_limit\":\"Compact<u64>\",\"storage_limit\":\"Compact<u32>\",\"valid_until\":\"Compact<u32>\"}:: Struct: failed on gas_limit: Compact<u64>:: u64: Negative number passed to unsigned type",
      "stack":
          Error: createType(Call):: Call: failed decoding evm.ethCall:: Struct: failed on args: {"action":"{\"_enum\":{\"Call\":\"H160\",\"Create\":\"Null\"}}","input":"Bytes","value":"Compact<u128>","gas_limit":"Compact<u64>","storage_limit":"Compact<u32>","valid_until":"Compact<u32>"}:: Struct: failed on gas_limit: Compact<u64>:: u64: Negative number passed to unsigned type
              at createTypeUnsafe (@polkadot+types@6.11.1/node_modules/@polkadot/types/create/createType.cjs:75:18)
              at TypeRegistry.createTypeUnsafe (@polkadot+types@6.11.1/node_modules/@polkadot/types/create/registry.cjs:417:45)
              at TypeRegistry.createType (@polkadot+types@6.11.1/node_modules/@polkadot/types/create/registry.cjs:409:17)
              at extrinsicFn (@polkadot+types@6.11.1/node_modules/@polkadot/types/metadata/decorate/extrinsics/createUnchecked.cjs:28:21)
              at Object.decorated [as ethCall] (@polkadot+api@6.11.1/node_modules/@polkadot/api/base/Decorate.cjs:462:22)
              at EvmRpcProvider.BaseProvider.prepareTransaction (/home/bodhi.js/eth-providers/lib/base-provider.js:354:47)
              at processTicksAndRejections (internal/process/task_queues.js:95:5)
              at async EvmRpcProvider.BaseProvider.sendRawTransaction (/home/bodhi.js/eth-providers/lib/base-provider.js:378:35)
              at async Router.call (/home/bodhi.js/eth-rpc-adapter/src/router.ts:16:24)
              at async HTTPServerTransport.routerHandler (/home/bodhi.js/eth-rpc-adapter/src/transports/server-transport.ts:60:13)
    }
```

reproduce by running latest bodhi and running the truffle example.

```
cd examples/truffle 
truffle migration --network mandala
```

**Comment by ntduan** [comment]
can you try `gaslimit: 34132001`, `gasPrice: 200786445289`

**Comment by gluneau** [comment]
test params:
```
    mandala: {
      provider: () =>
        new HDWalletProvider(
          ['0xa872f6cbd25a0e04a08b1e21098017a9e6194d101d75e13111f71410c59cd57f'],
          'http://127.0.0.1:8545'
        ),
      network_id: 595,
      gasPrice: 200786445289, // storage_limit = 100000, validUntil = 10000, 100000 << 32 | 10000
      gaslimit: 34132001,
      timeoutBlocks: 25,
      confirmations: 0
    }
```

results are the same:
```
➜  truffle git:(master) ✗ truffle migration --network mandala

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



Starting migrations...
======================
> Network name:    'mandala'
> Network id:      595
> Block gas limit: 15000000 (0xe4e1c0)


1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------

Error:  *** Deployment Failed ***

"Migrations" -- Error: createType(Call):: Call: failed decoding evm.ethCall:: Struct: failed on args: {"action":"{\"_enum\":{\"Call\":\"H160\",\"Create\":\"Null\"}}","input":"Bytes","value":"Compact<u128>","gas_limit":"Compact<u64>","storage_limit":"Compact<u32>","valid_until":"Compact<u32>"}:: Struct: failed on gas_limit: Compact<u64>:: u64: Negative number passed to unsigned type.
```

**Comment by ntduan** [comment]
Is the chain you are using up to date. What is the params of the eth_sendRawTransaction request?

**Comment by gluneau** [comment]
Here is the full param:

```
[1638856059125] DEBUG (1293514 on XPS-15-7590): incoming request
    id: 5499472567250289
    jsonrpc: "2.0"
    params: [
      "0xf903dc80852ebfce03e9836691b78080b903876080604052336000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555034801561005057600080fd5b50610327806100606000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c8063445df0ac146100465780638da5cb5b14610064578063fdacd57614610082575b600080fd5b61004e61009e565b60405161005b9190610179565b60405180910390f35b61006c6100a4565b60405161007991906101d5565b60405180910390f35b61009c60048036038101906100979190610221565b6100c8565b005b60015481565b60008054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b60008054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614610156576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040161014d906102d1565b60405180910390fd5b8060018190555050565b6000819050919050565b61017381610160565b82525050565b600060208201905061018e600083018461016a565b92915050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006101bf82610194565b9050919050565b6101cf816101b4565b82525050565b60006020820190506101ea60008301846101c6565b92915050565b600080fd5b6101fe81610160565b811461020957600080fd5b50565b60008135905061021b816101f5565b92915050565b600060208284031215610237576102366101f0565b5b60006102458482850161020c565b91505092915050565b600082825260208201905092915050565b7f546869732066756e6374696f6e206973207265737472696374656420746f207460008201527f686520636f6e74726163742773206f776e657200000000000000000000000000602082015250565b60006102bb60338361024e565b91506102c68261025f565b604082019050919050565b600060208201905081810360008301526102ea816102ae565b905091905056fea2646970667358221220cf9790d04b6e64e45f231a11198a5915bbd152e441fa71731e2691b9160048ef64736f6c634300080900338204caa0768ae68d9c3879abefee6baea33fb5f84346e57ff5c5fc897ad7727d0c62442ea046b07e7fa06fd78cf227402be4fa8648f32b9195891981935144964ee744e72f"
    ]
    method: "eth_sendRawTransaction"
[1638856059132] ERROR (1293514 on XPS-15-7590): request error
    methodName: "eth_sendRawTransaction"
    params: [
      "0xf903dc80852ebfce03e9836691b78080b903876080604052336000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555034801561005057600080fd5b50610327806100606000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c8063445df0ac146100465780638da5cb5b14610064578063fdacd57614610082575b600080fd5b61004e61009e565b60405161005b9190610179565b60405180910390f35b61006c6100a4565b60405161007991906101d5565b60405180910390f35b61009c60048036038101906100979190610221565b6100c8565b005b60015481565b60008054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b60008054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614610156576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040161014d906102d1565b60405180910390fd5b8060018190555050565b6000819050919050565b61017381610160565b82525050565b600060208201905061018e600083018461016a565b92915050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006101bf82610194565b9050919050565b6101cf816101b4565b82525050565b60006020820190506101ea60008301846101c6565b92915050565b600080fd5b6101fe81610160565b811461020957600080fd5b50565b60008135905061021b816101f5565b92915050565b600060208284031215610237576102366101f0565b5b60006102458482850161020c565b91505092915050565b600082825260208201905092915050565b7f546869732066756e6374696f6e206973207265737472696374656420746f207460008201527f686520636f6e74726163742773206f776e657200000000000000000000000000602082015250565b60006102bb60338361024e565b91506102c68261025f565b604082019050919050565b600060208201905081810360008301526102ea816102ae565b905091905056fea2646970667358221220cf9790d04b6e64e45f231a11198a5915bbd152e441fa71731e2691b9160048ef64736f6c634300080900338204caa0768ae68d9c3879abefee6baea33fb5f84346e57ff5c5fc897ad7727d0c62442ea046b07e7fa06fd78cf227402be4fa8648f32b9195891981935144964ee744e72f"
    ]
    err: {
      "type": "Error",
      "message": "createType(Call):: Call: failed decoding evm.ethCall:: Struct: failed on args: {\"action\":\"{\\\"_enum\\\":{\\\"Call\\\":\\\"H160\\\",\\\"Create\\\":\\\"Null\\\"}}\",\"input\":\"Bytes\",\"value\":\"Compact<u128>\",\"gas_limit\":\"Compact<u64>\",\"storage_limit\":\"Compact<u32>\",\"valid_until\":\"Compact<u32>\"}:: Struct: failed on gas_limit: Compact<u64>:: u64: Negative number passed to unsigned type",
      "stack":
          Error: createType(Call):: Call: failed decoding evm.ethCall:: Struct: failed on args: {"action":"{\"_enum\":{\"Call\":\"H160\",\"Create\":\"Null\"}}","input":"Bytes","value":"Compact<u128>","gas_limit":"Compact<u64>","storage_limit":"Compact<u32>","valid_until":"Compact<u32>"}:: Struct: failed on gas_limit: Compact<u64>:: u64: Negative number passed to unsigned type
              at createTypeUnsafe (/home/bodhi.js/common/temp/node_modules/.pnpm/@polkadot+types@6.11.1/node_modules/@polkadot/types/create/createType.cjs:75:18)
              at TypeRegistry.createTypeUnsafe (/home/bodhi.js/common/temp/node_modules/.pnpm/@polkadot+types@6.11.1/node_modules/@polkadot/types/create/registry.cjs:417:45)
              at TypeRegistry.createType (/home/bodhi.js/common/temp/node_modules/.pnpm/@polkadot+types@6.11.1/node_modules/@polkadot/types/create/registry.cjs:409:17)
              at extrinsicFn (/home/bodhi.js/common/temp/node_modules/.pnpm/@polkadot+types@6.11.1/node_modules/@polkadot/types/metadata/decorate/extrinsics/createUnchecked.cjs:28:21)
              at Object.decorated [as ethCall] (/home/bodhi.js/common/temp/node_modules/.pnpm/@polkadot+api@6.11.1/node_modules/@polkadot/api/base/Decorate.cjs:462:22)
              at EvmRpcProvider.BaseProvider.prepareTransaction (/home/bodhi.js/eth-providers/lib/base-provider.js:354:47)
              at processTicksAndRejections (internal/process/task_queues.js:95:5)
              at async EvmRpcProvider.BaseProvider.sendRawTransaction (/home/bodhi.js/eth-providers/lib/base-provider.js:378:35)
              at async Router.call (/home/bodhi.js/eth-rpc-adapter/src/router.ts:16:24)
              at async HTTPServerTransport.routerHandler (/home/bodhi.js/eth-rpc-adapter/src/transports/server-transport.ts:60:13)
    }
```

**Comment by ntduan** [comment]
The gaslimit I got is 0x6691b7（6721975）
![image](https://user-images.githubusercontent.com/7029338/144974109-c8347a59-8f39-47ff-9beb-cc1a065dde74.png)
I'll look into what went wrong.

**Comment by ntduan** [comment]
```
 mandala: {
      provider: () =>
        new HDWalletProvider(
          ['0xa872f6cbd25a0e04a08b1e21098017a9e6194d101d75e13111f71410c59cd57f'],
          'http://127.0.0.1:8545'
        ),
      network_id: 595,
      gasPrice: 200786445289, // storage_limit = 100000, validUntil = 10000, 100000 << 32 | 10000
      gaslimit: 34132001,
      timeoutBlocks: 25,
      confirmations: 0
    }
```
@gluneau  try `gaslimit => gasLimit` or 
![image](https://user-images.githubusercontent.com/7029338/144974779-8a056ed7-6769-444e-bf18-5b161af66b26.png)

**Comment by gluneau** [comment]
Updated with capital L, same results.
```
mandala: {
      provider: () =>
        new HDWalletProvider(
          ['0xa872f6cbd25a0e04a08b1e21098017a9e6194d101d75e13111f71410c59cd57f'],
          'http://127.0.0.1:8545'
        ),
      network_id: 595,
      gasPrice: 200786445289, // storage_limit = 100000, validUntil = 10000, 100000 << 32 | 10000
      gasLimit: 34132001,
      timeoutBlocks: 25,
      confirmations: 0
    }
```

**Comment by ntduan** [comment]
They have different parameters for different versions of the chain. Maybe this will work：
```
gasLimit, 2100001
gasPrice, 200786445289
```

**Comment by gluneau** [comment]
I tried that and it did not change anything.

**Comment by ermalkaleci** [comment]
This will return negative gas_limit
https://github.com/AcalaNetwork/bodhi.js/blob/f382707a18a6282048568b40c2a234b6a7f17a40/eth-providers/src/utils/transactionHelper.ts#L63

**Comment by ntduan** [comment]
> This will return negative gas_limit
> 
> https://github.com/AcalaNetwork/bodhi.js/blob/f382707a18a6282048568b40c2a234b6a7f17a40/eth-providers/src/utils/transactionHelper.ts#L63

Yes, it depends on the gaslimit and gasprice passed in
