### ISSUE TITLE
The contract code couldn't be stored, please check your gas limit..

### ISSUE THREAD

**Issue by gluneau** [AcalaNetwork/bodhi.js#186]
To reproduce:
```
git clone git@github.com:AcalaNetwork/kreatr-contracts.git
cd kreatr-contracts
yarn
yarn migrate-mandala
```

Log:
```
yarn run v1.22.5
warning package.json: No license field
$ truffle migrate --network mandala --f 2 -to 2 --compile-all --reset

Compiling your contracts...
===========================
> Compiling ./contracts/AddressUpgradeable.sol
> Compiling ./contracts/ContextUpgradeable.sol
> Compiling ./contracts/ECDSAUpgradeable.sol
> Compiling ./contracts/ERC1155BaseURI.sol
> Compiling ./contracts/ERC1155BurnableUpgradeable.sol
> Compiling ./contracts/ERC1155KREATRUser.sol
> Compiling ./contracts/ERC1155Upgradeable.sol
> Compiling ./contracts/ERC1271.sol
> Compiling ./contracts/ERC1271Validator.sol
> Compiling ./contracts/ERC165StorageUpgradeable.sol
> Compiling ./contracts/ERC165Upgradeable.sol
> Compiling ./contracts/HasContractURI.sol
> Compiling ./contracts/IERC1155MetadataURIUpgradeable.sol
> Compiling ./contracts/IERC1155ReceiverUpgradeable.sol
> Compiling ./contracts/IERC1155Upgradeable.sol
> Compiling ./contracts/IERC165Upgradeable.sol
> Compiling ./contracts/Initializable.sol
> Compiling ./contracts/LibPart.sol
> Compiling ./contracts/Migrations.sol
> Compiling ./contracts/Mint1155Validator.sol
> Compiling ./contracts/OwnableUpgradeable.sol
> Compiling ./contracts/StringsUpgradeable.sol
> Compiling ./contracts/draft-EIP712Upgradeable.sol
> Compiling ./mint/ERC1155Lazy.sol
> Compiling ./mint/IERC1155LazyMint.sol
> Compiling ./mint/LibERC1155LazyMint.sol
> Compiling ./royalties/AbstractRoyalties.sol
> Compiling ./royalties/LibRoyaltiesV2.sol
> Compiling ./royalties/RoyaltiesV2.sol
> Compiling ./royalties/RoyaltiesV2Impl.sol
> Compiling ./royalties/RoyaltiesV2Upgradeable.sol
> Artifacts written to acala/kreatr/contracts/build/contracts
> Compiled successfully using:
   - solc: 0.8.0+commit.c7dfd78e.Emscripten.clang



Starting migrations...
======================
> Network name:    'mandala'
> Network id:      595
> Block gas limit: 15000000 (0xe4e1c0)


2_deploy_contracts.js
=====================

   Replacing 'ERC1155KREATRUser'
   -----------------------------
   > transaction hash:    0x3d5ab3bb6fd38603b08309355221c9ad33f69c7836103159d3c43b5f0cca7d60

Error:  *** Deployment Failed ***

"ERC1155KREATRUser" -- The contract code couldn't be stored, please check your gas limit..

    at acala/kreatr/contracts/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:365:1
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Migration._deploy (acala/kreatr/contracts/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:70:1)
    at Migration._load (acala/kreatr/contracts/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:56:1)
    at Migration.run (acala/kreatr/contracts/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:217:1)
    at Object.runMigrations (acala/kreatr/contracts/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (acala/kreatr/contracts/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at runMigrations (acala/kreatr/contracts/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:253:1)
    at Object.run (acala/kreatr/contracts/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:223:1)
    at Command.run (acala/kreatr/contracts/node_modules/truffle/build/webpack:/packages/core/lib/command.js:183:1)
Truffle v5.4.17 (core: 5.4.17)
Node v14.18.2
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ntduan** [comment]
I encountered this error on my first run: `The send transactions "from" field must be defined`

But after that it runs all right.

```
> Network name:    'localhost'
> Network id:      595
> Block gas limit: 15000000 (0xe4e1c0)


2_deploy_contracts.js
=====================

   Replacing 'ERC1155KREATRUser'
   -----------------------------
   > transaction hash:    0xda39d63b521321f8936ba2fa6c299e5e25ca207ba3b5dd203b22544102ecb55c
   > Blocks: 0            Seconds: 0
   > contract address:    0x97d99E019970F6A1Cc0b3CA41b1dB84F625F1C9c
   > block number:        9265
   > block timestamp:     1642030109
   > account:             0x75E480dB528101a381Ce68544611C169Ad7EB342
   > balance:             160.286501803408
   > gas used:            0 (0x0)
   > gas price:           0.000000001 gwei
   > value sent:          0 ETH
   > total cost:          0 ETH

ERC1155KREATRUser deployed to: 0x97d99E019970F6A1Cc0b3CA41b1dB84F625F1C9c
   > Saving artifacts
   -------------------------------------
   > Total cost:                   0 ETH


Summary
=======
> Total deployments:   1
> Final cost:          0 ETH
```

I am using localhost network

**Comment by Lawrence-Acala** [comment]
is this still an issue @ntduan ?

**Comment by Lawrence-Acala** [comment]
OK lets close this then.
