### ISSUE TITLE
Error: [number-to-bn] while converting number undefined to BN.js instance

### ISSUE THREAD

**Issue by gluneau** [AcalaNetwork/bodhi.js#202]
Is `eth_getBlockByNumber` not returning proper BIg Number?

`truffle migrate --network localhost --f 2 -to 2 --compile-all --reset`

```
> transaction hash:    0x4d05a6020ff0077bf456c5aa11a8a4db2292b28235158bf67e75515f3465dd90
   ⠋ Blocks: 0            Seconds: 8
Error: Error: [number-to-bn] while converting number undefined to BN.js instance, error: invalid number value. Value must be an integer, hex string, BN or BigNumber instance. Note, decimals are not supported. Given value: "undefined"
    at Object.toBN (.config/yarn/global/node_modules/truffle/build/webpack:/node_modules/web3-utils/lib/utils.js:60:1)
    at outputBigNumberFormatter (.config/yarn/global/node_modules/truffle/build/webpack:/node_modules/web3-core-helpers/lib/formatters.js:64:1)
    at outputTransactionFormatter (.config/yarn/global/node_modules/truffle/build/webpack:/node_modules/web3-core-helpers/lib/formatters.js:205:1)
    at .config/yarn/global/node_modules/truffle/build/webpack:/node_modules/web3-core-helpers/lib/formatters.js:268:1
    at Array.forEach (<anonymous>)
    at Method.outputBlockFormatter (.config/yarn/global/node_modules/truffle/build/webpack:/node_modules/web3-core-helpers/lib/formatters.js:266:1)
    at Method.web3.eth.getBlock.method.outputFormatter (.config/yarn/global/node_modules/truffle/build/webpack:/packages/interface-adapter/dist/shim/overloads/ethereum.js:38:1)
    at Method.formatOutput (.config/yarn/global/node_modules/truffle/build/webpack:/node_modules/web3-eth/node_modules/web3-core-method/lib/index.js:147:1)
    at sendTxCallback (.config/yarn/global/node_modules/truffle/build/webpack:/node_modules/web3-eth/node_modules/web3-core-method/lib/index.js:523:1)
    at .config/yarn/global/node_modules/truffle/build/webpack:/node_modules/web3/node_modules/web3-core-requestmanager/lib/index.js:308:1
    at contracts/node_modules/@trufflesuite/web3-provider-engine/index.js:240:9
    at contracts/node_modules/async/internal/once.js:12:16
    at replenish (contracts/node_modules/async/internal/eachOfLimit.js:61:25)
    at contracts/node_modules/async/internal/eachOfLimit.js:71:9
    at eachLimit (contracts/node_modules/async/eachLimit.js:43:36)
    at contracts/node_modules/async/internal/doLimit.js:9:16
    at end (contracts/node_modules/@trufflesuite/web3-provider-engine/index.js:217:5)
    at Request._callback (contracts/node_modules/@trufflesuite/web3-provider-engine/subproviders/rpc.js:72:5)
    at Request.self.callback (contracts/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.<anonymous> (contracts/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:400:28)
    at IncomingMessage.<anonymous> (contracts/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Truffle v5.3.2 (core: 5.3.2)
Node v14.18.2
```

RPC response:

```
[1640206068326] DEBUG (1468963 on XPS-15-7590): incoming request
    id: 19
    jsonrpc: "2.0"
    params: [
      "0x62",
      false
    ]
    method: "eth_getBlockByNumber"

[1640206068358] DEBUG (1468963 on XPS-15-7590): request completed
    id: 19
    jsonrpc: "2.0"
    result: {
      "hash": "0x6a0b35e02e7f4a836c51c8fd33b1c65f3599ff16cd3b3b4226e75fc81e29726f",
      "parentHash": "0x5d8f8b6381523212a0a06e818a3baad55ecdc20c0ea204c4ac832a6fe7310a6f",
      "number": "0x62",
      "stateRoot": "0xae85401db5af8f45faa423aa53ff7f51c821e794ef3fcbfde764166a5f8e3f95",
      "transactionsRoot": "0x9d59738bfa903de9abc14ec3c0753246e45532e3f993a7ac2e64a982079710ac",
      "timestamp": "0x17de3e66920",
      "nonce": "0x0000000000000000",
      "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
      "difficulty": "0x0",
      "gasLimit": "0xe4e1c0",
      "gasUsed": "0x0",
      "miner": "0xF4cA11Ca834C9e2FB49f059aB71fB9C72dAd05f9",
      "author": "0xF4cA11Ca834C9e2FB49f059aB71fB9C72dAd05f9",
      "extraData": "",
      "baseFeePerGas": "0x0",
      "transactions": [
        {
          "blockHash": "0x6a0b35e02e7f4a836c51c8fd33b1c65f3599ff16cd3b3b4226e75fc81e29726f",
          "blockNumber": "0x62",
          "transactionIndex": "0x0",
          "hash": "0x4d05a6020ff0077bf456c5aa11a8a4db2292b28235158bf67e75515f3465dd90",
          "nonce": "0x1",
          "from": "0x75e480db528101a381ce68544611c169ad7eb342",
          "to": null,
          "value": "0x0"
        }
      ]
    }
```

**Comment by gluneau** [comment]
It was a truffle version issue.

```
➜  contracts git:(master) truffle version  
Truffle v5.3.2 (core: 5.3.2)
Solidity - 0.8.0 (solc-js)
Node v14.18.2
Web3.js v1.3.5

➜  contracts git:(master) yarn truffle version
yarn run v1.22.5
$ node_modules/.bin/truffle version
Truffle v5.4.17 (core: 5.4.17)
Solidity - 0.8.0 (solc-js)
Node v14.18.2
Web3.js v1.5.3
```
