### ISSUE TITLE
Miss uncles

### ISSUE THREAD

**Issue by zjb0807** [AcalaNetwork/bodhi.js#284]
```
blockscout    | 2022-02-23T06:32:06.178 application=indexer fetcher=block_catchup first_block_number=862 last_block_number=853 [error] ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Block.elixir_to_uncles/1
blockscout    |     (ethereum_jsonrpc 0.1.0) lib/ethereum_jsonrpc/block.ex:503: EthereumJSONRPC.Block.elixir_to_uncles(%{"author" => "0x69535cB2F9Db4FC5f2867A27a1eD8e6612F787bA", "difficulty" => 0, "extraData" => "", "gasLimit" => 1500000
0, "gasUsed" => 0, "hash" => "0xbc0bbac6af4e958e7a5d835c22494e5a8f4d6e39619cc6e92d3428f9227de011", "logsBloom" => "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "miner" => "0x69535cB2F9Db4FC5f2867A27a1eD8e6612F787bA", "mixHash" => "0x000000000
0000000000000000000000000000000000000000000000000000000", "nonce" => "0x0000000000000000", "number" => 853, "parentHash" => "0x0e46333e4e5cb8c7062340200a1c2150e7d4f13f7f2cad6598b5e81772c48b90", "receiptsRoot" => "0xd3f4cfc46d453b1ebc2e355
e469fa1cf47137e9e9ae5c9984c41e2f6a60569b9", "sha3Uncles" => "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347", "stateRoot" => "0x996780319509764f11dc26a95b5a3b1eaaa54454209a0d16ddb839ec89654dbf", "timestamp" => ~U[2022-
02-20 19:38:36Z], "transactions" => [], "transactionsRoot" => "0xd3f4cfc46d453b1ebc2e355e469fa1cf47137e9e9ae5c9984c41e2f6a60569b9"})
blockscout    |     (elixir 1.12.3) lib/enum.ex:3900: Enum.flat_map_list/2
```

https://eth.wiki/json-rpc/API `eth_getBlockByHash`

**Comment by zjb0807** [comment]
https://playground.open-rpc.org/
