### ISSUE TITLE
waffle dex example failed with latest mandala 

### ISSUE THREAD

**Issue by shunjizhan** [AcalaNetwork/bodhi.js#298]
waffle dex example failed with `acala/mandala-node:4d6a1610`, previously passed with `acala/mandala-node:e361c534`
can be reproduced locally and with CI https://github.com/AcalaNetwork/bodhi.js/runs/5458712675?check_suite_focus=true
```
 1) Dex
waffle-examples-test_1               |        swapWithExactSupply works:
waffle-examples-test_1               |      Error: -32603: VM Exception while processing transaction: execution revert InvalidTradingPath: 0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000012496e76616c696454726164696e6750617468
waffle-examples-test_1               |       at RpcCoder._checkError (/app/common/temp/node_modules/.pnpm/@polkadot+rpc-provider@6.11.1/node_modules/@polkadot/rpc-provider/coder/index.cjs:84:13)
waffle-examples-test_1               |       at RpcCoder.decodeResponse (/app/common/temp/node_modules/.pnpm/@polkadot+rpc-provider@6.11.1/node_modules/@polkadot/rpc-provider/coder/index.cjs:47:10)
waffle-examples-test_1               |       at WsProvider.value (/app/common/temp/node_modules/.pnpm/@polkadot+rpc-provider@6.11.1/node_modules/@polkadot/rpc-provider/ws/index.cjs:260:90)
waffle-examples-test_1               |       at W3CWebSocket.value [as onmessage] (/app/common/temp/node_modules/.pnpm/@polkadot+rpc-provider@6.11.1/node_modules/@polkadot/rpc-provider/ws/index.cjs:240:153)
waffle-examples-test_1               |       at W3CWebSocket._dispatchEvent [as dispatchEvent] (/app/common/temp/node_modules/.pnpm/yaeti@0.0.6/node_modules/yaeti/lib/EventTarget.js:107:17)
waffle-examples-test_1               |       at W3CWebSocket.onMessage (/app/common/temp/node_modules/.pnpm/websocket@1.0.34/node_modules/websocket/lib/W3CWebSocket.js:234:14)
waffle-examples-test_1               |       at WebSocketConnection.<anonymous> (/app/common/temp/node_modules/.pnpm/websocket@1.0.34/node_modules/websocket/lib/W3CWebSocket.js:205:19)
waffle-examples-test_1               |       at WebSocketConnection.emit (node:events:520:28)
waffle-examples-test_1               |       at WebSocketConnection.emit (node:domain:475:12)
waffle-examples-test_1               |       at WebSocketConnection.processFrame (/app/common/temp/node_modules/.pnpm/websocket@1.0.34/node_modules/websocket/lib/WebSocketConnection.js:554:26)
waffle-examples-test_1               |       at /app/common/temp/node_modules/.pnpm/websocket@1.0.34/node_modules/websocket/lib/WebSocketConnection.js:323:40
waffle-examples-test_1               |       at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

**Comment by zjb0807** [comment]
https://github.com/AcalaNetwork/predeploy-contracts/releases/tag/v4.1.0
https://github.com/AcalaNetwork/predeploy-contracts/releases/tag/v3.1.0
https://github.com/AcalaNetwork/predeploy-contracts/releases/tag/v2.1.0

update `@acala-network/contracts`
