### ISSUE TITLE
return the error message instead of error index

### ISSUE THREAD

**Issue by zjb0807** [AcalaNetwork/bodhi.js#342]
```
{"level":20,"time":1648824912201,"pid":28,"hostname":"7673b738547b","id":3966362797572,"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"from":"0xeb4ffd6eaf0baccd5616b9e4042bd117bc03169a","value":"0xfe7e0cde8321023","gasPrice":"0x2eadc4000a","data":null,"to":"0x896c12e689665283530bd1ece3c29af55e23bb46"}],"msg":"incoming request"}
{"level":50,"time":1648824912206,"pid":28,"hostname":"7673b738547b","err":{"type":"RpcError","message":"-32603: execution fatal: Module { index: 130, error: 14, message: None }","stack":"RpcError: -32603: execution fatal: Module { index: 130, error: 14, message: None }\n    at RpcCoder._checkError (/app/common/temp/node_modules/.pnpm/@polkadot+rpc-provider@7.14.4-6/node_modules/@polkadot/rpc-provider/coder/index.cjs:76:13)\n    at RpcCoder.decodeResponse (/app/common/temp/node_modules/.pnpm/@polkadot+rpc-provider@7.14.4-6/node_modules/@polkadot/rpc-provider/coder/index.cjs:38:10)\n    at WsProvider.value (/app/common/temp/node_modules/.pnpm/@polkadot+rpc-provider@7.14.4-6/node_modules/@polkadot/rpc-provider/ws/index.cjs:290:90)\n    at W3CWebSocket.value [as onmessage] (/app/common/temp/node_modules/.pnpm/@polkadot+rpc-provider@7.14.4-6/node_modules/@polkadot/rpc-provider/ws/index.cjs:270:153)\n    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/app/common/temp/node_modules/.pnpm/yaeti@0.0.6/node_modules/yaeti/lib/EventTarget.js:107:17)\n    at W3CWebSocket.onMessage (/app/common/temp/node_modules/.pnpm/websocket@1.0.34/node_modules/websocket/lib/W3CWebSocket.js:234:14)\n    at WebSocketConnection.<anonymous> (/app/common/temp/node_modules/.pnpm/websocket@1.0.34/node_modules/websocket/lib/W3CWebSocket.js:205:19)\n    at WebSocketConnection.emit (node:events:520:28)\n    at WebSocketConnection.emit (node:domain:475:12)\n    at WebSocketConnection.processFrame (/app/common/temp/node_modules/.pnpm/websocket@1.0.34/node_modules/websocket/lib/WebSocketConnection.js:554:26)"},"methodName":"eth_estimateGas","params":[{"from":"0xeb4ffd6eaf0baccd5616b9e4042bd117bc03169a","value":"0xfe7e0cde8321023","gasPrice":"0x2eadc4000a","data":null,"to":"0x896c12e689665283530bd1ece3c29af55e23bb46"}],"msg":"request error"}
{"level":20,"time":1648824912208,"pid":28,"hostname":"7673b738547b","id":3966362797572,"jsonrpc":"2.0","error":{"code":6969,"message":"Error: -32603: execution fatal: Module { index: 130, error: 14, message: None }"},"msg":"request completed"}
```

**Comment by zjb0807** [comment]
```
{"level":20,"time":1649096157829,"pid":28,"hostname":"7673b738547b","method":"eth_estimateGas","params":[{"gasPrice":"0x2eb060000a","from":"0x3bc7f2e458ac4e55f941c458cfd8c6851a591b4f","to":"0xd11de1f930ea1f7dd0290fe3a2e35b9c91aefb37","data":"0x25394645000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000be010000000001006a496322abf9a50dcffeb28bc63f847cb9142464c973146624bee3f2005f2fe47bc44d31b0cc53285ce45ec5ca500181ad880647922f7e3e99c1fcb0185aeb040000000001000000010001000000000000000000000000000000000000000000000000000000000000000400000000023b5f7900000000000000000000000000000000000000000000546f6b656e42726964676502000b000000000000000000000000854cb6d416181e7d6a308b3118943c17c488cd5c0000"}],"id":52,"jsonrpc":"2.0","msg":"incoming request"}
{"level":50,"time":1649096157835,"pid":28,"hostname":"7673b738547b","err":{"type":"RpcError","message":"-32603: VM Exception while processing transaction: execution revert governance action already consumed: 0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000022676f7665726e616e636520616374696f6e20616c726561647920636f6e73756d656400000000000000000000000000000000000000000000000…","stack":"RpcError: -32603: VM Exception while processing transaction: execution revert governance action already consumed: 0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000022676f7665726e616e636520616374696f6e20616c726561647920636f6e73756d656400000000000000000000000000000000000000000000000…\n    at RpcCoder._checkError (/app/common/temp/node_modules/.pnpm/@polkadot+rpc-provider@7.14.4-6/node_modules/@polkadot/rpc-provider/coder/index.cjs:76:13)\n    at RpcCoder.decodeResponse (/app/common/temp/node_modules/.pnpm/@polkadot+rpc-provider@7.14.4-6/node_modules/@polkadot/rpc-provider/coder/index.cjs:38:10)\n    at WsProvider.value (/app/common/temp/node_modules/.pnpm/@polkadot+rpc-provider@7.14.4-6/node_modules/@polkadot/rpc-provider/ws/index.cjs:290:90)\n    at W3CWebSocket.value [as onmessage] (/app/common/temp/node_modules/.pnpm/@polkadot+rpc-provider@7.14.4-6/node_modules/@polkadot/rpc-provider/ws/index.cjs:270:153)\n    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/app/common/temp/node_modules/.pnpm/yaeti@0.0.6/node_modules/yaeti/lib/EventTarget.js:107:17)\n    at W3CWebSocket.onMessage (/app/common/temp/node_modules/.pnpm/websocket@1.0.34/node_modules/websocket/lib/W3CWebSocket.js:234:14)\n    at WebSocketConnection.<anonymous> (/app/common/temp/node_modules/.pnpm/websocket@1.0.34/node_modules/websocket/lib/W3CWebSocket.js:205:19)\n    at WebSocketConnection.emit (node:events:520:28)\n    at WebSocketConnection.emit (node:domain:475:12)\n    at WebSocketConnection.processFrame (/app/common/temp/node_modules/.pnpm/websocket@1.0.34/node_modules/websocket/lib/WebSocketConnection.js:554:26)"},"methodName":"eth_estimateGas","params":[{"gasPrice":"0x2eb060000a","from":"0x3bc7f2e458ac4e55f941c458cfd8c6851a591b4f","to":"0xd11de1f930ea1f7dd0290fe3a2e35b9c91aefb37","data":"0x25394645000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000be010000000001006a496322abf9a50dcffeb28bc63f847cb9142464c973146624bee3f2005f2fe47bc44d31b0cc53285ce45ec5ca500181ad880647922f7e3e99c1fcb0185aeb040000000001000000010001000000000000000000000000000000000000000000000000000000000000000400000000023b5f7900000000000000000000000000000000000000000000546f6b656e42726964676502000b000000000000000000000000854cb6d416181e7d6a308b3118943c17c488cd5c0000"}],"msg":"request error"}
{"level":20,"time":1649096157836,"pid":28,"hostname":"7673b738547b","id":52,"jsonrpc":"2.0","error":{"code":6969,"message":"Error: -32603: VM Exception while processing transaction: execution revert governance action already consumed: 0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000022676f7665726e616e636520616374696f6e20616c726561647920636f6e73756d656400000000000000000000000000000000000000000000000…"},"msg":"request completed"}
```

**Comment by ntduan** [comment]
@zjb0807 
```
"call": {
            "description": "eth call",
            "params": [
                {
                    "name": "data",
                    "type": "CallRequest"
                },
                {
                    "name": "at",
                    "type": "BlockHash",
                    "isHistoric": true,
                    "isOptional": true
                }
            ],
            "type": "Raw",
            "isSubscription": false,
            "jsonrpc": "evm_call",
            "method": "call",
            "section": "evm"
        },
```

If the return type is an enum, it will be easier to parse the error message

**Comment by zjb0807** [comment]
```
60405180606001604052806027815260200161024c602791396100ba565b9392505050565b3b151590565b90565b60006100917f360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc546001600160a01b031690565b905090565b3660008037600080366000845af43d6000803e8080156100b5573d6000f35b3d6000fd5b6060833b61011e5760405162461bcd60e51b815260206004820152602660248201527f416464726573733a2064656c65676174652063616c6c20746f206e6f6e2d636f6044820152651b9d1c9858dd60d21b60648201526084015b60405180910390fd5b600080856001600160a01b03168560405161013991906101cc565b600060405180830381855af49150503d8060008114610174576040519150601f19603f3d011682016040523d82523d6000602084013e610179565b606091505b5091509150610189828286610193565b9695505050505050565b606083156101a257508161004e565b8251156101b25782518084602001fd5b8160405162461bcd60e51b815260040161011591906101e8565b600082516101de81846020870161021b565b9190910192915050565b602081526000825180602084015261020781604085016020870161021b565b601f01601f19169190910160400192915050565b60005b8381101561023657818101518382015260200161021e565b83811115610245576000848401525b5050505056fe416464726573733a206c6f772d6c6576656c2064656c65676174652063616c6c206661696c6564a2646970667358221220c651652cc0041da7a6ccfbb62ab4d69a33d006e787e6a41c09cd2b8fb857905d64736f6c63430008040033","msg":"request completed"}
{"level":20,"time":1649097753993,"pid":28,"hostname":"7673b738547b","id":682,"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0x0000000000000000000100000000000000000080","data":"0x01ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000"},"0x3af76"],"msg":"incoming request"}
{"level":50,"time":1649097753996,"pid":28,"hostname":"7673b738547b","err":{"type":"RpcError","message":"-32603: VM Exception while processing transaction: execution revert: 0x","stack":"RpcError: -32603: VM Exception while processing transaction: execution revert: 0x\n    at RpcCoder._checkError (/app/common/temp/node_modules/.pnpm/@polkadot+rpc-provider@7.14.4-6/node_modules/@polkadot/rpc-provider/coder/index.cjs:76:13)\n    at RpcCoder.decodeResponse (/app/common/temp/node_modules/.pnpm/@polkadot+rpc-provider@7.14.4-6/node_modules/@polkadot/rpc-provider/coder/index.cjs:38:10)\n    at WsProvider.value (/app/common/temp/node_modules/.pnpm/@polkadot+rpc-provider@7.14.4-6/node_modules/@polkadot/rpc-provider/ws/index.cjs:290:90)\n    at W3CWebSocket.value [as onmessage] (/app/common/temp/node_modules/.pnpm/@polkadot+rpc-provider@7.14.4-6/node_modules/@polkadot/rpc-provider/ws/index.cjs:270:153)\n    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/app/common/temp/node_modules/.pnpm/yaeti@0.0.6/node_modules/yaeti/lib/EventTarget.js:107:17)\n    at W3CWebSocket.onMessage (/app/common/temp/node_modules/.pnpm/websocket@1.0.34/node_modules/websocket/lib/W3CWebSocket.js:234:14)\n    at WebSocketConnection.<anonymous> (/app/common/temp/node_modules/.pnpm/websocket@1.0.34/node_modules/websocket/lib/W3CWebSocket.js:205:19)\n    at WebSocketConnection.emit (node:events:520:28)\n    at WebSocketConnection.emit (node:domain:475:12)\n    at WebSocketConnection.processFrame (/app/common/temp/node_modules/.pnpm/websocket@1.0.34/node_modules/websocket/lib/WebSocketConnection.js:554:26)"},"methodName":"eth_call","params":[{"to":"0x0000000000000000000100000000000000000080","data":"0x01ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000"},"0x3af76"],"msg":"request error"}
{"level":20,"time":1649097753997,"pid":28,"hostname":"7673b738547b","id":682,"jsonrpc":"2.0","error":{"code":6969,"message":"Error: -32603: VM Exception while processing transaction: execution revert: 0x"},"msg":"request completed"}

```

**Comment by zjb0807** [comment]
```
{"level":50,"time":1649098464036,"pid":28,"hostname":"7673b738547b","err":{"type":"RpcError","message":"-32603: VM Exception while processing transaction: execution revert: 0x","stack":"RpcError: -32603: VM Exception while processing transaction: execution revert: 0x\n    at RpcCoder._checkError (/app/common/temp/node_modules/.pnpm/@polkadot+rpc-provider@7.14.4-6/node_modules/@polkadot/rpc-provider/coder/index.cjs:76:13)\n    at RpcCoder.decodeResponse (/app/common/temp/node_modules/.pnpm/@polkadot+rpc-provider@7.14.4-6/node_modules/@polkadot/rpc-provider/coder/index.cjs:38:10)\n    at WsProvider.value (/app/common/temp/node_modules/.pnpm/@polkadot+rpc-provider@7.14.4-6/node_modules/@polkadot/rpc-provider/ws/index.cjs:290:90)\n    at W3CWebSocket.value [as onmessage] (/app/common/temp/node_modules/.pnpm/@polkadot+rpc-provider@7.14.4-6/node_modules/@polkadot/rpc-provider/ws/index.cjs:270:153)\n    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/app/common/temp/node_modules/.pnpm/yaeti@0.0.6/node_modules/yaeti/lib/EventTarget.js:107:17)\n    at W3CWebSocket.onMessage (/app/common/temp/node_modules/.pnpm/websocket@1.0.34/node_modules/websocket/lib/W3CWebSocket.js:234:14)\n    at WebSocketConnection.<anonymous> (/app/common/temp/node_modules/.pnpm/websocket@1.0.34/node_modules/websocket/lib/W3CWebSocket.js:205:19)\n    at WebSocketConnection.emit (node:events:520:28)\n    at WebSocketConnection.emit (node:domain:475:12)\n    at WebSocketConnection.processFrame (/app/common/temp/node_modules/.pnpm/websocket@1.0.34/node_modules/websocket/lib/WebSocketConnection.js:554:26)"},"methodName":"eth_call","params":[{"to":"0x478dEFc2Fc2be13a505dafBDF1e5400847E2efF6","data":"0x01ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000"},"0x3afaf"],"msg":"request error"}
```

**Comment by zjb0807** [comment]
@ntduan Maybe I can do it in rust side. I'll try it.
