### ISSUE TITLE
No response received from RPC endpoint in 30s

### ISSUE THREAD

**Issue by zjb0807** [AcalaNetwork/bodhi.js#349]
```
{"level":20,"time":1649382942614,"pid":28,"hostname":"67823ecd0767","0":{"id":0,"jsonrpc":"2.0","error":{"code":6969,"message":"Error: No response received from RPC endpoint in 30s"}},"msg":"request completed"}
{"level":20,"time":1649382942614,"pid":28,"hostname":"67823ecd0767","0":{"id":0,"jsonrpc":"2.0","error":{"code":6969,"message":"Error: No response received from RPC endpoint in 30s"}},"msg":"request completed"}
{"level":20,"time":1649382942615,"pid":28,"hostname":"67823ecd0767","0":{"id":0,"jsonrpc":"2.0","error":{"code":6969,"message":"Error: No response received from RPC endpoint in 30s"}},"msg":"request completed"}
{"level":20,"time":1649382942615,"pid":28,"hostname":"67823ecd0767","0":{"id":0,"jsonrpc":"2.0","error":{"code":6969,"message":"Error: No response received from RPC endpoint in 30s"}},"msg":"request completed"}
{"level":20,"time":1649382942615,"pid":28,"hostname":"67823ecd0767","0":{"id":0,"jsonrpc":"2.0","error":{"code":6969,"message":"Error: No response received from RPC endpoint in 30s"}},"msg":"request completed"}
{"level":20,"time":1649382942616,"pid":28,"hostname":"67823ecd0767","0":{"id":0,"jsonrpc":"2.0","error":{"code":6969,"message":"Error: No response received from RPC endpoint in 30s"}},"msg":"request completed"}
{"level":20,"time":1649382942616,"pid":28,"hostname":"67823ecd0767","0":{"id":0,"jsonrpc":"2.0","error":{"code":6969,"message":"Error: No response received from RPC endpoint in 30s"}},"msg":"request completed"}
{"level":20,"time":1649382942616,"pid":28,"hostname":"67823ecd0767","0":{"id":0,"jsonrpc":"2.0","error":{"code":6969,"message":"Error: No response received from RPC endpoint in 30s"}},"msg":"request completed"}
{"level":20,"time":1649382942617,"pid":28,"hostname":"67823ecd0767","0":{"id":0,"jsonrpc":"2.0","error":{"code":6969,"message":"Error: No response received from RPC endpoint in 30s"}},"msg":"request completed"}
{"level":20,"time":1649382942617,"pid":28,"hostname":"67823ecd0767","0":{"id":0,"jsonrpc":"2.0","error":{"code":6969,"message":"Error: No response received from RPC endpoint in 30s"}},"msg":"request completed"}
{"level":20,"time":1649382942617,"pid":28,"hostname":"67823ecd0767","0":{"id":0,"jsonrpc":"2.0","error":{"code":6969,"message":"Error: No response received from RPC endpoint in 30s"}},"msg":"request completed"}
{"level":20,"time":1649382942617,"pid":28,"hostname":"67823ecd0767","0":{"id":0,"jsonrpc":"2.0","error":{"code":6969,"message":"Error: No response received from RPC endpoint in 30s"}},"msg":"request completed"}
{"level":20,"time":1649382942618,"pid":28,"hostname":"67823ecd0767","0":{"id":0,"jsonrpc":"2.0","error":{"code":6969,"message":"Error: No response received from RPC endpoint in 30s"}},"msg":"request completed"}
{"level":20,"time":1649382942618,"pid":28,"hostname":"67823ecd0767","0":{"id":0,"jsonrpc":"2.0","error":{"code":6969,"message":"Error: No response received from RPC endpoint in 30s"}},"msg":"request completed"}
{"level":20,"time":1649382942618,"pid":28,"hostname":"67823ecd0767","0":{"id":0,"jsonrpc":"2.0","error":{"code":6969,"message":"Error: No response received from RPC endpoint in 30s"}},"msg":"request completed"}
{"level":20,"time":1649382942618,"pid":28,"hostname":"67823ecd0767","0":{"id":0,"jsonrpc":"2.0","error":{"code":6969,"message":"Error: No response received from RPC endpoint in 30s"}},"msg":"request completed"}
/app/common/temp/node_modules/.pnpm/@polkadot+rpc-provider@7.14.4-6/node_modules/@polkadot/rpc-provider/ws/index.cjs:394
              handler.callback(new Error(`No response received from RPC endpoint in ${TIMEOUT_S}s`), undefined);
                               ^
Error: No response received from RPC endpoint in 30s
    at WsProvider.value (/app/common/temp/node_modules/.pnpm/@polkadot+rpc-provider@7.14.4-6/node_modules/@polkadot/rpc-provider/ws/index.cjs:394:32)
    at Timeout._onTimeout (/app/common/temp/node_modules/.pnpm/@polkadot+rpc-provider@7.14.4-6/node_modules/@polkadot/rpc-provider/ws/index.cjs:503:166)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ntduan** [comment]
https://github.com/AcalaNetwork/bodhi.js/pull/350 

Downgrading the rpc provider to 7.12.1 will avoid the 30 second timeout limit.
