### ISSUE TITLE
createType failed

### ISSUE THREAD

**Issue by zjb0807** [AcalaNetwork/bodhi.js#353]
```
{"level":20,"time":1649583349798,"pid":29,"hostname":"dd6ee5a77117","0":{…: {\"phase\":\"FrameSystemPhase\",\"event\":\"Event\",\"topics\":\"Vec<H256>\"}:: decodeU8a: failed at 0xe3234f433914d4cfcf846491ec5a7831… on topics: Vec<H256>:: Vec length 1416799235778640807438118673265233557808799771191999166257749099353881033501421918759938946205828042124305340685817414490019724998592822872592163 exceeds 65536","stack":"Error: createType(Vec<FrameSystemEventRecord>):: decodeU8a: failed at 0x00020000008202e3234f433914d4cfcf…: {\"phase\":\"FrameSystemPhase\",\"event\":\"Event\",\"topics\":\"Vec<H256>\"}:: decodeU8a: failed at 0xe3234f433914d4cfcf846491ec5a7831… on topics: Vec<H256>:: Vec length 1416799235778640807438118673265233557808799771191999166257749099353881033501421918759938946205828042124305340685817414490019724998592822872592163 exceeds 65536\n    at createTypeUnsafe (/app/common/temp/node_modules/.pnpm/@polkadot+types-create@7.14.4-6/node_modules/@polkadot/types-create/create/type.cjs:73:18)\n    at TypeRegistry.createTypeUnsafe (/app/common/temp/node_modules/.pnpm/@polkadot+types@7.14.4-6/node_modules/@polkadot/types/create/registry.cjs:323:46)\n    at EvmRpcProvider.BaseProvider.queryStorage (/app/eth-providers/lib/base-provider.js:109:46)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at runNextTicks (node:internal/process/task_queues:65:3)\n    at processImmediate (node:internal/timers:437:9)\n    at async Promise.all (index 3)\n    at async EvmRpcProvider.BaseProvider._getBlock (/app/eth-providers/lib/base-provider.js:168:59)\n    at async Eip1193BridgeImpl.eth_getBlockByNumber (/app/eth-rpc-adapter/src/eip1193-bridge.ts:182:21)"},"methodName":"eth_getBlockByNumber","params":["0x1F147",true],"msg":"request error"}
```

Failed to query earlier blocks. Is the metadata corresponding to the runtime not cached? @ntduan

**Comment by ntduan** [comment]
How to reproduce?

https://github.com/AcalaNetwork/bodhi.js/pull/355

I added test cases, but it is working fine
