### ISSUE TITLE
WebSocket is not connected

### ISSUE THREAD

**Issue by zjb0807** [AcalaNetwork/bodhi.js#424]
```
{"level":20,"time":1652076250128,"pid":28,"hostname":"7b44323dee52","0":{"id":0,"jsonrpc":"2.0","error":{"code":6969,"message":"Error: WebSocket is not connected"}},"1":{"id":1,"jsonrpc":"2.0","error":{"code":6969,"message":"Error: WebSocket is not connected"}},"2":{"id":2,"jsonrpc":"2.0","error":{"code":6969,"message":"Error: WebSocket is not connected"}},"3":{"id":3,"jsonrpc":"2.0","error":{"code":6969,"message":"Error: WebSocket is not connected"}},"4":{"id":4,"jsonrpc":"2.0","error":{"code":6969,"message":"Error: WebSocket is not connected"}},"5":{"id":5,"jsonrpc":"2.0","error":{"code":6969,"message":"Error: WebSocket is not connected"}},"6":{"id":6,"jsonrpc":"2.0","error":{"code":6969,"message":"Error: WebSocket is not connected"}},"7":{"id":7,"jsonrpc":"2.0","error":{"code":6969,"message":"Error: WebSocket is not connected"}},"8":{"id":8,"jsonrpc":"2.0","error":{"code":6969,"message":"Error: WebSocket is not connected"}},"9":{"id":9,"jsonrpc":"2.0","error":{"code":6969,"message":"Error: WebSocket is not connected"}},"msg":"request completed"}
```

**Comment by zjb0807** [comment]
<img width="872" alt="image" src="https://user-images.githubusercontent.com/16496415/167354177-07ce70fe-238a-4651-82c4-7984697d28c6.png">

@shunjizhan Should we return an error code of 500?

**Comment by zjb0807** [comment]
```
/app/common/temp/node_modules/.pnpm/@polkadot+rpc-provider@8.1.1/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:214
        const error = new Error(`disconnected from ${(0, _classPrivateFieldLooseBase2.default)(this, _endpoints)[_endpoints][(0, _classPrivateFieldLooseBase2.default)(this, _endpointIndex)[_endpointIndex]]}: ${event.code}:: ${event.reason || (0, _errors.getWSErrorString)(event.code)}`);
                      ^
Error: disconnected from wss://karura.api.onfinality.io/ws?apikey=c16c91bb-5ef3-4725-9ea0-8a510c8f1135: 1006:: Connection dropped by remote peer.
    at W3CWebSocket.value (/app/common/temp/node_modules/.pnpm/@polkadot+rpc-provider@8.1.1/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:214:23)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/app/common/temp/node_modules/.pnpm/yaeti@0.0.6/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onClose (/app/common/temp/node_modules/.pnpm/websocket@1.0.34/node_modules/websocket/lib/W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (/app/common/temp/node_modules/.pnpm/websocket@1.0.34/node_modules/websocket/lib/W3CWebSocket.js:201:17)
    at WebSocketConnection.emit (node:events:527:28)
    at WebSocketConnection.emit (node:domain:475:12)
    at WebSocketConnection.handleSocketClose (/app/common/temp/node_modules/.pnpm/websocket@1.0.34/node_modules/websocket/lib/WebSocketConnection.js:389:14)
    at TLSSocket.emit (node:events:539:35)
    at TLSSocket.emit (node:domain:475:12)
    at node:net:709:12
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.18
```

**Comment by shunjizhan** [comment]
@zjb0807 is it still an issue?

**Comment by zjb0807** [comment]
This error is gone now
