### ISSUE TITLE
better error handling of bodhi signer

### ISSUE THREAD

**Issue by shunjizhan** [AcalaNetwork/bodhi.js#508]
when insufficient balance, got `TypeError: code.substr is not a function` error, should return appropriate error msg

```
Uncaught (in promise) TypeError: code.substr is not a function
    at decodeMessage (handleTxResponse.ts:8:30)
    at handleTxResponse.ts:64:27
    at Array.forEach (<anonymous>)
    at handleTxResponse.ts:38:10
    at new Promise (<anonymous>)
    at handleTxResponse (handleTxResponse.ts:31:10)
    at Signer.ts:278:11
    at decorateMethod.js:69:24
```

**Comment by ntduan** [comment]
Not sure how to reproduce this error. This pr #512  may have fixed this error.

**Comment by shunjizhan** [comment]
I don't remember where I saw it either, but we can close it and if it happens again we can revisit
