### ISSUE TITLE
subquery-node fails - Cannot find module 'http'

### ISSUE THREAD

**Issue by qezz** [AcalaNetwork/bodhi.js#541]
Hi guys. 
I'm trying to set up the `evm-subql` containers in relation to Acala & Karura.
For now, focusing on Karura.

I use the following configuration
* subquery-node - `onfinality/subql-node:v1.7.0`
* qraphql-engine - `onfinality/subql-query:v1.4.0`
* for subql-node, `-f=/app/project-karura-1780000.yaml`
* `--db-schema=acala_evm`. Not sure where it comes from, or whether it's important or not.
* I run Karura node outside of docker, but it shouldn't be related to this issue

EDIT 1: Also tried to run `yarn && yarn build` beforehand, but it didn't help

My `docker-compose.yaml` is as following

```yaml
version: "3.9"
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - /path/to/volume/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  subquery-node:
    image: onfinality/subql-node:v1.7.0
    depends_on:
      postgres:
        condition: service_started
    ports:
      - 3000:3000
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - /path/to/volume/bodhi.js/evm-subql:/app
    command:
      - -f=/app/project-karura-1780000.yaml
      - --network-endpoint=ws://<LOCAL_IP>:9944
      - --db-schema=acala_evm
      - --debug
      - --log-level=debug

  graphql-engine:
    image: onfinality/subql-query:v1.4.0
    ports:
      - 3001:3001
    depends_on:
      - postgres
      - subquery-node
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      PORT: 3001
    command:
      - --name=acala_evm
      - --playground
      - --indexer=http://subquery-node:3000

```

The `subquery-node` service starts fine, but I observe this warning:

```
2022-08-16T09:38:54.404Z <dictionary> WARN failed to fetch specVersion result 
Error: Only absolute URLs are supported
    at new ApolloError (/usr/local/lib/node_modules/@subql/node/node_modules/@apollo/client/errors/errors.cjs:34:28)
    at /usr/local/lib/node_modules/@subql/node/node_modules/@apollo/client/core/core.cjs:1595:19
    at both (/usr/local/lib/node_modules/@subql/node/node_modules/@apollo/client/utilities/utilities.cjs:986:53)
    at /usr/local/lib/node_modules/@subql/node/node_modules/@apollo/client/utilities/utilities.cjs:979:72
    at new Promise (<anonymous>)
    at Object.then (/usr/local/lib/node_modules/@subql/node/node_modules/@apollo/client/utilities/utilities.cjs:979:24)
    at Object.error (/usr/local/lib/node_modules/@subql/node/node_modules/@apollo/client/utilities/utilities.cjs:987:49)
    at notifySubscription (/usr/local/lib/node_modules/@subql/node/node_modules/zen-observable/lib/Observable.js:140:18)
    at onNotify (/usr/local/lib/node_modules/@subql/node/node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.error (/usr/local/lib/node_modules/@subql/node/node_modules/zen-observable/lib/Observable.js:240:7)
```

The following logs look OK to me 

```
2022-08-16T09:38:54.406Z <subql-node> INFO Node started on port: 3000 
2022-08-16 09:38:54        REGISTRY: Unknown signed extensions SetEvmOrigin found, treating them as no-effect
2022-08-16T09:38:54.568Z <BlockDispatcherService> INFO Enqueing blocks 1780000...1780099, total 100 blocks 
2022-08-16T09:38:54.568Z <BlockDispatcherService> INFO fetch block [1780000,1780099], total 100 blocks 
2022-08-16T09:38:54.575Z <BlockDispatcherService> INFO Enqueing blocks 1780100...1780199, total 100 blocks 
2022-08-16T09:38:54.575Z <BlockDispatcherService> INFO Enqueing blocks 1780200...1780299, total 100 blocks 
2022-08-16T09:38:54.575Z <BlockDispatcherService> INFO Enqueing blocks 1780300...1780399, total 100 blocks 
2022-08-16T09:38:56.658Z <BlockDispatcherService> INFO fetch block [1780100,1780199], total 100 blocks 
2022-08-16T09:38:56.664Z <BlockDispatcherService> INFO Enqueing blocks 1780400...1780499, total 100 blocks 
2022-08-16T09:38:56.684Z <db> DEBUG Executing (7a0e5803-327a-4e35-874f-1a78d8df301a): START TRANSACTION; 
2022-08-16T09:38:57.132Z <db> DEBUG Executing (7a0e5803-327a-4e35-874f-1a78d8df301a): ROLLBACK; 

```

Then it hits the error and exits:

```
2022-08-16T09:38:57.135Z <BlockDispatcherService> ERROR failed to index block at height 1780000 handleBlock(VMError: Cannot find module 'http'
    < long stacktrace here >

2022-08-16T09:38:57.135Z <db> DEBUG Executing (72847d43-519d-46c1-8964-11f4671f3869): START TRANSACTION; 
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

VMError: Cannot find module 'http'
    < long stacktrace here >
```

I put the stacktraces under the collapsible section:
<details>
<summary> The stacktraces </summary>

```
2022-08-16T09:38:57.135Z <BlockDispatcherService> ERROR failed to index block at height 1780000 handleBlock(VMError: Cannot find module 'http'
    at DefaultResolver.resolveFull (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:110:9)
    at DefaultResolver.resolveFull (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:316:16)
    at DefaultResolver.resolve (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:105:15)
    at VM2 Wrapper.apply (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/bridge.js:485:11)
    at requireImpl (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:84:28)
    at require (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:165:10)
    at /app/node_modules/@ethersproject/web/lib/geturl.js:43:30
    at VM2 Wrapper.apply (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/bridge.js:485:11)
    at IndexerSandbox.run (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/nodevm.js:425:23)
    at DefaultResolver.loadJS (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:203:7)) 
VMError: Cannot find module 'http'
    at DefaultResolver.resolveFull (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:110:9)
    at DefaultResolver.resolveFull (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:316:16)
    at DefaultResolver.resolve (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:105:15)
    at VM2 Wrapper.apply (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/bridge.js:485:11)
    at requireImpl (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:84:28)
    at require (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:165:10)
    at /app/node_modules/@ethersproject/web/lib/geturl.js:43:30
    at VM2 Wrapper.apply (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/bridge.js:485:11)
    at IndexerSandbox.run (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/nodevm.js:425:23)
    at DefaultResolver.loadJS (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:203:7)
2022-08-16T09:38:57.135Z <db> DEBUG Executing (72847d43-519d-46c1-8964-11f4671f3869): START TRANSACTION; 
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

VMError: Cannot find module 'http'
    at DefaultResolver.resolveFull (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:110:9)
    at DefaultResolver.resolveFull (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:316:16)
    at DefaultResolver.resolve (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:105:15)
    at VM2 Wrapper.apply (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/bridge.js:485:11)
    at requireImpl (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:84:28)
    at require (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:165:10)
    at /app/node_modules/@ethersproject/web/lib/geturl.js:43:30
    at VM2 Wrapper.apply (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/bridge.js:485:11)
    at IndexerSandbox.run (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/nodevm.js:425:23)
    at DefaultResolver.loadJS (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:203:7) {
  code: 'ENOTFOUND',
  handler: 'handleBlock',
  handlerArgs: '[{"block":{"header":{"parentHash":"0xbd204b2c5893413fe74063bb71abe1b1675e53b60343d8a03ccbe3784d559c9b","number":1780000,"stateRoot":"0xcd9390f6d4c7cf360f3db453e56a8a4d0d1897b55c95cf7fe878d8a55e5c3f63","extrinsicsRoot":"0xcb5928df13812ba0c7d33ca5c8b46ea139b8423963b9e3db4a688ec42b6b4c52","digest":{"logs":[{"preRuntime":["0x61757261","0x3d89320800000000"]},{"seal":["0x61757261","0x8c92204116ee99f66f5187b91e06000bf781d0cf5b2452b84126a5e2347dd51561db83a69b1107c327ffda8a6542af3acd60c47b69e216f627c0f03cf9491384"]}]}},"extrinsics":["0x280401000b030de1408001","0x1575041e00e902d5c91a745ceecebdd0444dc9d57124cb61aae494b7e239557aa589afe1b6d26d7ea46c0024a9a782c26dd9416a2b1f95d76dbf51c32ecf5adfe2b742c06ef422cb508fb2d829338c892e2c01fff0d414d263f9d49d54f948fce6fe1c4af7f66855bf9ac8080661757261203c893208000000000561757261010172294d8330af47a47ad87e60f231a829a944e8b96bca92ebfd194f7ea15e0865fd022076319197ec1f71b700c60583107c4543e4203653d54d6f64e9ee6bd38da0f8bb00a546618ddf6ed6801ebe7dc2450ab6658f39e770ba8acfa73acbff6dbe67b56500005000d0b456f5a4efb16ffa83d00700008072f59e80836e41082802a0843ee95656da0f372b74d9a8db4cbca0bf7f409ff4c856f5a4efb16ffa83d00700009424e8030000d1070000d4070000dc070000e7070000250800002c0800002f0800003b0800009d015d00e4cb071549282f080000d00700005501e803000000900100009001000000000000000000016455cde4ca6d02a93383c596703ae8110024ba2a2b26b543fba21d7122e7678d005039278c0400000000000000000000005039278c04000000000000000000009d015d02375331e1e9c22c080000d00700005501e803000000900100009001000000000000000000016005b0655e524f5d74053690156c53bba27ec2e722b6c5256ab40875a3797e88005039278c0400000000000000000000005039278c04000000000000000000009d015d0f87f2992da1f4d0070000e70700005501e80300000090010000900100000000000000000001f0d0a946c657f4a6c9793274d6bb305244a3e5a69d889ac22d013c4f949a0d84005039278c0400000000000000000000005039278c04000000000000000000009d015e04d2a15ab51127e8030000d00700005501e80300000090010000900100000000000000000001be9a2e01061cf1b3a53ef1624d84141eb9ee7554924c805d7d3989603d94d393005039278c0400000000000000000000005039278c04000000000000000000009d015e057a605f506cfcd4070000d00700005501e8030000009001000090010000000000000000000181aaa4c1054bbdff287d5d1b60e4880b9d5662856a13bdf5e30b2b8ff6d85516005039278c0400000000000000000000005039278c04000000000000000000009d015e1deb2e6f4cbe90d1070000d00700005501080000000090010000040000000000000000000001c0e02a84273abb4a3bded82cb42fb62a7c8a49902896c6c61de55e2312f87cb2005039278c0400000000000000000000005039278c04000000000000000000009d015e32290e8150361fd00700002c0800005501e8030000009001000090010000000000000000000151520ff3ab24ac9eb1176d118078416a4fbcf3aaded70f0ef2bc5f08c30e4b73005039278c0400000000000000000000005039278c04000000000000000000009d015e36c65ca123d5fbd0070000dc0700005501e80300000090010000900100000000000000000001ea285e789f66a11b3c08fdd7ba1cec5a266f151235efc70427b22a5eab9bced4005039278c0400000000000000000000005039278c04000000000000000000009d015e4f36708366b722d0070000e80300005501e80300000090010000900100000000000000000001ca0daec4d5f78e7b499dbef00426eaea3fc1252d2af8c861ac89297415f7acd8005039278c0400000000000000000000005039278c04000000000000000000009d015e59e4ea9f4ac743d0070000d10700005501e80300000090010000900100000000000000000001f5e420d40eaabb71aa834447d71907780a58b83e79604aca0c2eeec4101d80a8005039278c0400000000000000000000005039278c04000000000000000000009d015e8b652b2ae6ed1ddc070000d00700005501e803000000900100009001000000000000000000019deaaeeea565c83ea7a4c0eeb361cc7e0f4c3491fdf45f015e2601c3083419ab005039278c0400000000000000000000005039278c04000000000000000000009d015ea03dcb5ca43dffd00700003b0800005501e80300000090010000900100000000000000000001df64bb353bcffd02353c588352733e1dd6091e96ce0dfd471ef66b518d93f724005039278c0400000000000000000000005039278c04000000000000000000009d015eaf9c742868bbe225080000d00700005501e80300000090010000900100000000000000000001d475232a0d8e6dcc5b6975c582d98fb720fa591fe06830d169f8d0c4bc4e1bfa005039278c0400000000000000000000005039278c04000000000000000000009d015eb7edc4cbc65e03d0070000d40700005501e803000000900100009001000000000000000000018a70aa2587885f9691ff4462796d21e786979d85eec370fef920b07d85b6c6ad005039278c0400000000000000000000005039278c04000000000000000000009d015ec44036e9963cf2d0070000250800005501e80300000090010000900100000000000000000001a57110be3217a73b62e24a844281a201996081c3f17d7ef1d4963fab72592b7c005039278c0400000000000000000000005039278c04000000000000000000009d015ee7436e0cc64fbf3b080000d00700005501e8030000009001000090010000000000000000000115e0952a59adfcc58044acbb920d3d093fdeb9848e67d42b9c29030698b57bd2005039278c0400000000000000000000005039278c040000000000000000000079035f04b49d95320d9021994c850f25b8e3852d030000a000005000000a00000000c8000000c800000a0000000a000000100e0000580200000000500000c8000000e87648170000001e00000000000000005039278c0400000000000000000000005039278c0400000000000000000000e8030000009001001e00000000000000009001008070000000000000000000000a0000000a0000000a00000001000000010500000001c8000000060000005802000002000000580200000200000059000000000000001e0000002800000000c817a804000000000200000014000000a1015f0bbfa02d10d2b43ae7070000d00700005501e8030000009001000090010000000000000000000167c1d46cc200fd1b0b7374fdc7748d41f3d319be36649ad0cdbc885ec7018d59005039278c0400000000000000000000005039278c0400000000000000000000a1015f0e9ec0f2d53c37cad00700002f0800005501e803000000900100009001000000000000000000010f6af1c9693a4947564977e75816f59089e0156470d9580a398387e5b2cf80b3005039278c0400000000000000000000005039278c0400000000000000000000990180001380f456971fcd8a66f360d9809ab37db39883e6e4d6bddb4c3b98aee5ce6da962bc807501ebb65c814a5013c14efd66229d3c57d2c2c43e3ae679b642b8bfc1b13e558095a33387383a7a2909e4d0110346b2bec04c6f3d7c42a8dfb5966d64bfa3be9d150180004280825b5f8a8607d9f39be4dfc1ea5f60c2bcf7c14a6869f1a05b2c7a718b35ad73800de26c83195cdffd48ef9389bf4a667e80d04f58a2f6f5e9e9e606f127a822fa1501800048803cd09dde7755c9d20e31fcf1fce1a0a7c88268172a7230915d153d4f31f9403980aa964743f1c26fdce0ca62831a5ef855ed9f23f72af1ee07ecccb783f9cd4c24e0800060805768f5038a71a7c6f02efd50a224753255e0a91bdd791cc011b6399450874da44c5e7b9012096b41c4eb3aaf947f6ea42908000099018000c280acf99734fd64d59113d6f2b80492d9fe70b98218eb4277623f802d47dbd16c368032f882af52a4587c9582cb6c1e401d92efd781c918597a082cb97cee1ef5b962802e66f6a8f156599676985b3fef8e2e0c17259703f3558a5942e889df2914c7cb1501800104806f857024dd5e3843973fd14d16d229b01874bc315c1afa4fd72c2cf64548123e80bc000a22c5ab4f2b1e2597957143c1e460bd89498cee9781f1eb556e5893495a15018001108061fd9f36dd18bece49f13f875a60d8620da6bfc7e0e2f9401c1d227bd1cb67fa80ee8d7c6cbd1d75d97780cdfcf57da6bde42d34f2987c3acc9efe8d2735c086df1501800280800738ef13ec0ee25e78235460eb4edcd0e782758dd861c3891a3c598e9834626980e6993ac78dd32c460d4def1206bc3c5576ac86059ecb38c61256e0615fe77a6da10280046c80a5d101a55b9778714fc23627cce68cb8aad807beb505fbe794a7677f39aa89ca80312cf228be8cddad1232ae0209315f740488c502f15805c6602f9346f249ca82808f83f0d8e6399e9f9d10c3c89b614e318848dfb7ecead89b137ab1fe2fa968f9803dd18dc44283312bfc730a7a0947591b43d7c5beec433f7174779a2879ad89f8804b791c2206adbc0c2879135321e1ed756ef3a16803f812c37a93d6007f6463a7990180081480f72845058f493684c9a6dbd2c42fd399b399d734f195db936f40819462c3f2958059b70cf88ec2b6c3ad2cd8e2e064aec97508d33273f2c5a06375114cf3fb939f8021790fe1492ec1760c013d017773c04a08126067da915f43d0165edfc77b16efec8008408065620d4f22df66fb223290c30e4d2807631bfa66598d97b58599dce4f356df02585628b8ad2696ed532c0800002408d0070000e707000015018008408096a95a28a00ec0d3bcd2da622900ec963ee43f9e1dca48af2fa927b0d852bdc18079a23898b080ca7421ed0e82d0d3d9d123b65713bfe1606f3af0066cd6039ff71d02800a30805bcb19260e9bac4a196743998633bfdab740cb29984e3c5265190eb81318920f8071d86f16d8ddeae170c75364ffb6b1b1b1c0158c5b17bb6f4624155eb14171cd80c85fed164803340f73b3223f5e6fed27caa87bc5a28a54e6a8b37a93245b4c3d80cd495cd1089b2a45ae2cd0c949ea02441b42087d430476f73fa4822106007f4b9901800a8080a62aabb00bc802f9bfd5e73ea75421c7f83926a65e4a39e6f2a6c7d03a0a2dc5801d53e6957294c0087899910be8be8e10411117d5ba38b520abdaacdf9663c40980044d049d1a8cdc5bacfed44b5239d8e2e57772be67ceebd4aaa85856f7d918739101800c2078767bbb460270642b5bcaf032ea04d56aadc7217647a32b0be90300000400808d09419630a3e3bbdd6be03eabfc2bc2e258415389724c6be149eeb46d8c6c2c8056f7d2fa23644da2ef3e22cbfe9bd649063edd9a60763c8e03a10b7694f255072503801117806083fccc5ad9489e8fffd469466a4206a743d8dbbc8fb301059daa1d198c862880a5d22222218150c4d44b008ed3035e705d9f7689bdefa86cbf8ee58165131a9980d517703e673302ab471e749d54a6aa6c52fd8181970a5333b0ef0ca3002964ff80c364167df70c3b526bdf70f813f5ab4c5288b673c652a89dcfa2f80ad938d0628022d83924b6b61bbfd83f9b60ddff15b468b959cca85964a268e56d20924f8fc6803b47aa6e7a43c30e6c4c4bf81f3d83a5e9246e3652400aadf866787437111235150180210080ed3878929879400526549ff04b96ffaa5a983d4dea0c10c192df442971fb024980c78098142a180b6af11b28a28cccf630a8ef34bc9ac09b82deacae44d83f5a3a150180400880163580fceb5af6ac2d1d83b121e2ad96cb34c35cbd113b26d1635e0fa2cc520b80500c3e1fadcbf6a663b0c8c37a91eb3b24271e37efb19904106badc43a7010b81d0280650080e61636000e5d559a5a9dbb50e776c7b8ac4041d9c9f202633aa42b99e386e6fc80e1be6afcbe52e5fce196a6f28faa51319eddcd80f00f57f02d3a60dadc36a25e805d5915c2e9b3583659123d919fb38c189d393b13f417582c7f7e8d1da47cfeb4801d8c6bd56b9fbc94a728b0a2426bcb15979b1dff2dd66515d152a91124ea933f99018081208043217cc219d96ce6728204fab74319ac99eddb463e32a3a8114f5ee79bb1a2ac80d2adad7148411e8bb295d271768c949ad5e8e180d09ebff8c6514c13d8cf4e9c80fc267ca1537b30672f949b6bdeb598e6cf68b827e9e4e097a9dc87ea18bf1d954d0880ffff80fb600df850b1dad445d813a20f65442a3ddf2f7a387c1f2828e428cf3f41591280cdfb48617c756887ed0b00d5395c86216a347179396dea74e7fe1292ad64124d801f782d60359401fee5fbf1c317865b9419db487b4a053330a2a9d8ecc12b856e8033b6a411e9cd4d514ff5287c0189f842c232fe441f2befb8b80618a668966c9180a113dff91c6b1de65fc69f09d614fe7ee36ee637a8a9a0cde6e4f9a4471280a48005f31e0a5968228f4a93b394dc057334e9d631d40f84b277225881a161b7b991803ff03aa95f25ab8e0d99013f761f2d3bdd8fc7d7f2fbd28d397fb2ae73c20c958089cc2572fb24e96c5c9a296389192931280432f469a2cf277e74367921ac439980e3c9ac5551ae63368084cb1e875b9a83d2b72f0508a899c9f91782d7dc7ff4ef80fd371b7982fb3844aa62ee8a42a28f22'... 5577 more characters
}

```

</details>

Not sure if it's a bug or not. I tried to re-pack the subquery-node image with the http module installed (`npm i -g http`), but no luck.

**Comment by qezz** [comment]
It started to index stuff after I brought back the `--unsafe` option for the `subquery-node` command.
My current set up is as following:

```yaml
  subquery-node:
    # image: onfinality/subql-node:v1.7.0
    build:
      dockerfile: evm-subql.Dockerfile
      context: .
      target: evm-subql-index
    depends_on:
      # ...
    ports:
      - 3000:3000
    restart: always
    environment:
      # ...
    volumes:
      - /path/to/bodhi.js/evm-subql:/app
    command:
      - -f=/app/project-karura-1780000.yaml
      - --network-endpoint=ws://10.130.0.140:9944
      - --db-schema=acala_evm
      - --debug
      - --log-level=debug
      - --unsafe
```

P.S. In the `evm-subql.Dockerfile` I re-use the `onfinality/subql-node:v1.7.0` image.

Closing the issue as resolved.
