### ISSUE TITLE
VMError: Cannot find module 'http'

### ISSUE THREAD

**Issue by mcf-rocks** [AcalaNetwork/bodhi.js#544]
I've almost got this working, without docker, yet something is missing, some http module?

Very similar to previous issue.

Any clue?

```karura@a7:~/bodhi.js/evm-subql$ yarn index
yarn run v1.22.19
$ npx subql-node -f . --local --batch-size 200 --db-schema acala_evm --port 3030
2022-08-17T15:47:44.269Z <configure> WARN Note that argument --local has been deprecated 
2022-08-17T15:47:44.456Z <indexer> INFO indexer manager start 
2022-08-17 16:47:44        REGISTRY: Unknown signed extensions SetEvmOrigin found, treating them as no-effect
2022-08-17T15:47:44.715Z <store> INFO Historical state is disabled 
2022-08-17T15:47:44.799Z <dictionary> WARN failed to fetch specVersion result Error: Only absolute URLs are supported
2022-08-17T15:47:44.801Z <subql-node> INFO Node started on port: 3030 
2022-08-17 16:47:44        REGISTRY: Unknown signed extensions SetEvmOrigin found, treating them as no-effect
2022-08-17T15:47:44.920Z <BlockDispatcherService> INFO Enqueing blocks 1780000...1780199, total 200 blocks 
2022-08-17T15:47:44.920Z <BlockDispatcherService> INFO fetch block [1780000,1780199], total 200 blocks 
2022-08-17T15:47:44.932Z <BlockDispatcherService> INFO Enqueing blocks 1780200...1780399, total 200 blocks 
2022-08-17T15:47:44.932Z <BlockDispatcherService> INFO Enqueing blocks 1780400...1780599, total 200 blocks 
2022-08-17T15:47:44.932Z <BlockDispatcherService> INFO Enqueing blocks 1780600...1780799, total 200 blocks 
2022-08-17T15:47:48.028Z <BlockDispatcherService> INFO fetch block [1780200,1780399], total 200 blocks 
2022-08-17T15:47:48.357Z <BlockDispatcherService> ERROR failed to index block at height 1780000 handleBlock(VMError: Cannot find module 'http'
    at DefaultResolver.resolveFull (/home/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:110:9)
    at DefaultResolver.resolveFull (/home/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:316:16)
    at DefaultResolver.resolve (/home/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:105:15)
    at VM2 Wrapper.apply (/home/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/vm2/lib/bridge.js:485:11)
    at requireImpl (/home/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:84:28)
    at require (/home/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:165:10)
    at /home/karura/bodhi.js/evm-subql/node_modules/@ethersproject/web/lib/geturl.js:43:30
    at VM2 Wrapper.apply (/home/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/vm2/lib/bridge.js:485:11)
    at IndexerSandbox.run (/home/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/vm2/lib/nodevm.js:425:23)
    at DefaultResolver.loadJS (/home/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:203:7)) VMError: Cannot find module 'http'
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

VMError: Cannot find module 'http'
    at DefaultResolver.resolveFull (/home/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:110:9)
    at DefaultResolver.resolveFull (/home/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:316:16)
    at DefaultResolver.resolve (/home/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:105:15)
    at VM2 Wrapper.apply (/home/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/vm2/lib/bridge.js:485:11)
    at requireImpl (/home/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:84:28)
    at require (/home/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:165:10)
    at /home/karura/bodhi.js/evm-subql/node_modules/@ethersproject/web/lib/geturl.js:43:30
    at VM2 Wrapper.apply (/home/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/vm2/lib/bridge.js:485:11)
    at IndexerSandbox.run (/home/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/vm2/lib/nodevm.js:425:23)
    at DefaultResolver.loadJS (/home/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:203:7) {
  code: 'ENOTFOUND',
  handler: 'handleBlock'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```

**Comment by mcf-rocks** [comment]
this seems to work.
```
yarn index --unsafe 
```

**Comment by mcf-rocks** [comment]
obviously i'm just happy it's working -- but what is the relationship between --unsafe and a missing module?

**Comment by shunjizhan** [comment]
@mcf-rocks @qezz sorry for the outdated doc, I am updating it. And [this subquery doc](https://academy.subquery.network/run_publish/references.html#unsafe) explains what `--unsafe` is, and why it is required for `http` module. Let me know if it doesn't make sense or if you have any other questions.

![Screen Shot 2022-08-18 at 13 14 13](https://user-images.githubusercontent.com/16548786/185299243-13d8aea4-a5c2-4f74-86c3-1b7afc9651fe.png)

**Comment by qezz** [comment]
Hey @shunjizhan thanks for the clarification
