### ISSUE TITLE
yarn query - create apollo server failed

### ISSUE THREAD

**Issue by mcf-rocks** [AcalaNetwork/bodhi.js#549]
```
$ cd ~/bodhi.js/evm-subql
$ DB_USER=postgres DB_PASS=zzz DB_DATABASE=karura DB_HOST=localhost DB_PORT=5432 yarn query --unsafe
yarn run v1.22.19
$ PORT=3001 npx subql-query --name acala_evm --playground --indexer=http://localhost:3030 --debug --unsafe
2022-08-19T09:38:38.230Z <nestjs> INFO Starting Nest application... 
2022-08-19T09:38:38.238Z <nestjs> INFO AppModule dependencies initialized 
2022-08-19T09:38:38.238Z <nestjs> INFO ConfigureModule dependencies initialized 
2022-08-19T09:38:38.239Z <nestjs> INFO GraphqlModule dependencies initialized 
2022-08-19T09:38:38.239Z <subql-query> INFO Started playground at http://localhost:3001 
/home/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/query/dist/graphql/graphql.module.js:55
            throw new Error(`create apollo server failed, ${e.message}`);
                  ^

Error: create apollo server failed, unknown project name acala_evm
    at GraphqlModule.onModuleInit (/home/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/query/dist/graphql/graphql.module.js:55:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async callModuleInitHook (/home/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/query/node_modules/@nestjs/core/hooks/on-module-init.hook.js:51:9)
    at async NestApplication.callInitHook (/home/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/query/node_modules/@nestjs/core/nest-application-context.js:178:13)
    at async NestApplication.init (/home/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/query/node_modules/@nestjs/core/nest-application.js:96:9)
    at async NestApplication.listen (/home/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/query/node_modules/@nestjs/core/nest-application.js:158:33)
    at async /home/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/query/dist/main.js:29:5
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by zjb0807** [comment]
https://github.com/AcalaNetwork/bodhi.js/blob/2860f29e68f5f4b80564f9ce2bf8979a6a5cf7be/evm-subql/package.json#L12-L13

the `--name acala_evm` should be the same as `--db-schema acala_evm`

**Comment by mcf-rocks** [comment]
This is karura....

I have been able to get it working by changing the file package.json:
```
$ DB_USER=postgres DB_PASS=applesandpearsheaven DB_DATABASE=karura DB_HOST=localhost DB_PORT=5432 PORT=3001 npx subql-query --name **public** --playground --indexer=http://localhost:3030 --debug
```

It seems the database that karura gets made the tables are all under "public" schema, but acala they are under "acala
_evm" schema.

**Comment by zjb0807** [comment]
> It seems the database that karura gets made the tables are all under "public" schema, but acala they are under "acala
_evm" schema.

This is because your parameter is `--name public`.
If you start the `index` with `--db-schema karura_evm`, you can start the `query` with `--name karura_evm`

**Comment by mcf-rocks** [comment]
I am going to try and move things around manually - is it the case that subqueries table should always be public schema?

**Comment by zjb0807** [comment]
https://github.com/subquery/subql/pull/683
I think this table is deprecated.  Not sure it can be dropped

**Comment by mcf-rocks** [comment]
Thx for your help... curious, what is the reason for schemas rather than just separate database?

**Comment by mcf-rocks** [comment]
Even when I specify --db_schema karura_evm on the indexer, it still makes those tables as public.

**Comment by zjb0807** [comment]
Is the new data stored in the schemas tables? or still public tables

**Comment by mcf-rocks** [comment]
the public tables .... it started populating again from 0... so i stopped it and move the tables back.

**Comment by ayudh37** [comment]
try starting your postgres service before the other services
