### ISSUE TITLE
Having a problem when syncing schema 

### ISSUE THREAD

**Issue by mcf-rocks** [AcalaNetwork/bodhi.js#602]
Any ideas what? cheers.
```
$ subql-node -f ./project.yaml --batch-size 30 --db-schema acala_evm --log-level debug --port 4040 --unsafe --unsafe
2022-12-12T18:55:58.973Z <subql-node> WARN UNSAFE MODE IS ENABLED. This is not recommended for most projects and will not be supported by our hosted service 
2022-12-12T18:55:59.447Z <indexer> INFO indexer manager start 
2022-12-12 18:55:59        REGISTRY: Unknown signed extensions SetEvmOrigin found, treating them as no-effect
2022-12-12T18:55:59.700Z <store> INFO Historical state is disabled 
2022-12-12T18:56:00.981Z <store> ERROR Having a problem when syncing schema 
Error
    at Query.run (/mnt/fast1/ACALA_DATA/acala/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)
    at /mnt/fast1/ACALA_DATA/acala/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/sequelize/lib/sequelize.js:313:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.sync (/mnt/fast1/ACALA_DATA/acala/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/sequelize/lib/model.js:976:11)
    at async Sequelize.sync (/mnt/fast1/ACALA_DATA/acala/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/sequelize/lib/sequelize.js:377:9)
    at async StoreService.syncSchema (/mnt/fast1/ACALA_DATA/acala/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/@subql/node-core/dist/indexer/store.service.js:204:9)
    at async StoreService.init (/mnt/fast1/ACALA_DATA/acala/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/@subql/node-core/dist/indexer/store.service.js:48:13)
    at async ProjectService.initDbSchema (/mnt/fast1/ACALA_DATA/acala/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/dist/indexer/project.service.js:175:9)
    at async ProjectService.init (/mnt/fast1/ACALA_DATA/acala/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/dist/indexer/project.service.js:66:13)
    at async bootstrap (/mnt/fast1/ACALA_DATA/acala/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/dist/main.js:40:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mcf-rocks** [comment]
That's it i think - deleted the database, created a new one, and it appears to be working.
