### ISSUE TITLE
Nothing in postgres for Karura 

### ISSUE THREAD

**Issue by mcf-rocks** [AcalaNetwork/bodhi.js#604]
Question - I've been running the new indexer and it is fully synced
```
Dec 15 14:45:44 a12 yarn[1495886]: 2022-12-15T14:45:44.368Z <benchmark> INFO Fully synced, waiting for new blocks
Dec 15 14:45:45 a12 yarn[1495886]: 2022-12-15T14:45:45.954Z <BlockDispatcherService> INFO Enqueing blocks 3276221...3276221, total 1 blocks
Dec 15 14:45:45 a12 yarn[1495886]: 2022-12-15T14:45:45.954Z <BlockDispatcherService> INFO fetch block [3276221,3276221], total 1 blocks
```
but there is nothing in the database:
```
root@a12:~# psql -h localhost -U postgres -p 5432 -d karura -W 
Password: 
psql (13.6 (Ubuntu 13.6-1.pgdg20.04+1+b1))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

karura=# select count(*) from karura_evm.transaction_receipts;
 count 
-------
     0
(1 row)

karura=# select count(*) from karura_evm.logs;
 count 
-------
     0
(1 row)
```
is it possible or is there problem?

**Comment by mcf-rocks** [comment]
this error in the log
```
Dec 15 14:56:22 a12 yarn[2548084]: 2022-12-15 14:56:22        REGISTRY: Unknown signed extensions SetEvmOrigin found, treating them as no-effect
Dec 15 14:56:22 a12 yarn[2548084]: 2022-12-15T14:56:22.919Z <store> INFO Historical state is disabled
Dec 15 14:56:23 a12 yarn[2548084]: 2022-12-15T14:56:23.030Z <dictionary> WARN failed to fetch specVersion result
Dec 15 14:56:23 a12 yarn[2548084]: Error: Only absolute URLs are supported
Dec 15 14:56:23 a12 yarn[2548084]:     at new ApolloError (/mnt/fast1/KARURA_DATA/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/@apollo/client/errors/errors.cjs:34:28)
Dec 15 14:56:23 a12 yarn[2548084]:     at /mnt/fast1/KARURA_DATA/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/@apollo/client/core/core.cjs:1595:19
Dec 15 14:56:23 a12 yarn[2548084]:     at both (/mnt/fast1/KARURA_DATA/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/@apollo/client/utilities/utilities.cjs:986:53)
Dec 15 14:56:23 a12 yarn[2548084]:     at /mnt/fast1/KARURA_DATA/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/@apollo/client/utilities/utilities.cjs:979:72
Dec 15 14:56:23 a12 yarn[2548084]:     at new Promise (<anonymous>)
Dec 15 14:56:23 a12 yarn[2548084]:     at Object.then (/mnt/fast1/KARURA_DATA/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/@apollo/client/utilities/utilities.cjs:979:24)
Dec 15 14:56:23 a12 yarn[2548084]:     at Object.error (/mnt/fast1/KARURA_DATA/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/@apollo/client/utilities/utilities.cjs:987:49)
Dec 15 14:56:23 a12 yarn[2548084]:     at notifySubscription (/mnt/fast1/KARURA_DATA/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/zen-observable/lib/Observable.js:140:18)
Dec 15 14:56:23 a12 yarn[2548084]:     at onNotify (/mnt/fast1/KARURA_DATA/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/zen-observable/lib/Observable.js:179:3)
Dec 15 14:56:23 a12 yarn[2548084]:     at SubscriptionObserver.error (/mnt/fast1/KARURA_DATA/karura/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/zen-observable/lib/Observable.js:240:7)
```

**Comment by shunjizhan** [comment]
`Error: Only absolute URLs are supported` should NOT be an issue, it appears all the time.

can you try sending this graphql query to the subquery endpoint, and see if it returns anything?
```
query {
  transactionReceipts {
    nodes {
      id
      to
      from
      transactionHash
      transactionIndex
      gasUsed
      logs {
        nodes {
          id
        }
      }
    }
  }
  logs {
    nodes {
      id,
      blockNumber,
      blockHash,
      transactionIndex,
      address,
      data,
      transactionHash,
      receipt {
        id
      }
    }
  }
}
```

**Comment by shunjizhan** [comment]
for example this is the result from the subquery we deployed, you can find the subquery url from [evm doc](https://evmdocs.acala.network/network/network-configuration)
![Screenshot 2022-12-16 at 15 00 01](https://user-images.githubusercontent.com/16548786/208041124-ca011adc-6910-438e-a2ea-aa05a71ca3b0.png)

**Comment by mcf-rocks** [comment]
```
# curl -g -X POST -H "Content-Type: application/json" -d '{"query":"query{ transactionReceipts { nodes { id to from transactionHash transactionIndex gasUsed logs { nodes { id } } } } logs { nodes { id, blockNumber, blockHash, transactionIndex, address, data, transactionHash, receipt { id } } } }" }' http://localhost:3001
{"data":{"transactionReceipts":{"nodes":[]},"logs":{"nodes":[]}}}```

**Comment by shunjizhan** [comment]
is it empty right after the indexer start? The first transaction happen at block `1818395`, so we will need to wait a little bit before there is tx in database

**Comment by mcf-rocks** [comment]
It now returns many rows, so I think Karura is all working.
