### ISSUE TITLE
Run `npx @acala-network/eth-rpc-adapter --endpoint ws://localhost:9944 --local-mode` failed

### ISSUE THREAD

**Issue by ntduan** [AcalaNetwork/bodhi.js#781]
```
npx @acala-network/eth-rpc-adapter --endpoint ws://localhost:9944 --local-mode

node:internal/bootstrap/switches/does_own_process_state:126
    cachedCwd = rawMethods.cwd();
                           ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd [as cwd] (node:internal/bootstrap/switches/does_own_process_state:126:28)
    at Object.<anonymous> (/Users/ntduan/.nvm/versions/node/v16.20.0/lib/node_modules/npm/node_modules/depd/index.js:25:24)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/Users/.nvm/versions/node/v16.20.0/lib/node_modules/npm/node_modules/agentkeepalive/lib/agent.js:6:19)
    at Module._compile (node:internal/modules/cjs/loader:1196:14) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}

```

**Comment by shunjizhan** [comment]
I think this is related to #767

**Comment by shunjizhan** [comment]
not sure why the error msg is different though, will take a look
