### ISSUE TITLE
Indexer is broken 2.6.5

### ISSUE THREAD

**Issue by z1z2z3z4z5z6** [AcalaNetwork/bodhi.js#794]
```
2023-07-31T15:56:08.602Z <BlockDispatcherService> INFO Enqueueing blocks 4103773...4103802, total 30 blocks 
2023-07-31T15:56:08.603Z <BlockDispatcherService> ERROR failed to index block at height 4103653 handleBlock(VMError: Cannot find module 'http'
    at CustomResolver.resolveFull (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:126:9)
    at CustomResolver.resolveFull (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:316:16)
    at CustomResolver.resolve (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:121:15)
    at resolve (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/nodevm.js:317:21)
    at VM2 Wrapper.apply (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/bridge.js:485:11)
    at requireImpl (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:90:19)
    at require (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:171:10)
    at /home/acala/bodhi.js/evm-subql/node_modules/@ethersproject/web/lib/geturl.js:43:30
    at VM2 Wrapper.apply (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/bridge.js:485:11)
    at IndexerSandbox.run (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/nodevm.js:497:23)) 
VMError: Cannot find module 'http'
    at CustomResolver.resolveFull (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:126:9)
    at CustomResolver.resolveFull (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:316:16)
    at CustomResolver.resolve (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:121:15)
    at resolve (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/nodevm.js:317:21)
    at VM2 Wrapper.apply (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/bridge.js:485:11)
    at requireImpl (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:90:19)
    at require (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:171:10)
    at /home/acala/bodhi.js/evm-subql/node_modules/@ethersproject/web/lib/geturl.js:43:30
    at VM2 Wrapper.apply (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/bridge.js:485:11)
    at IndexerSandbox.run (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/nodevm.js:497:23)
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

VMError: Cannot find module 'http'
    at CustomResolver.resolveFull (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:126:9)
    at CustomResolver.resolveFull (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:316:16)
    at CustomResolver.resolve (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:121:15)
    at resolve (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/nodevm.js:317:21)
    at VM2 Wrapper.apply (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/bridge.js:485:11)
    at requireImpl (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:90:19)
    at require (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:171:10)
    at /home/acala/bodhi.js/evm-subql/node_modules/@ethersproject/web/lib/geturl.js:43:30
    at VM2 Wrapper.apply (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/bridge.js:485:11)
    at IndexerSandbox.run (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/nodevm.js:497:23) {
  code: 'ENOTFOUND',
  handler: 'handleBlock',
  handlerArgs: '[{"block":{"header":{"parentHash":"0x0738999e2e2d4451ad84f25f8d8244c692fb37f0810e89f6e1de82409888c9d9","number":4103653,"stateRoot":"0x8736b4b5625e56537d3e5e8df3050587d2efc01de82af436b3c7e35c0fff3552","extrinsicsRoot":"0x8bc36105824fbc13082f436dd138d808a78bc37e48f0772038a22a8d0c4e0272","digest":{"logs":[{"preRuntime":["0x61757261","0xae8b650800000000"]},{"seal":["0x61757261","0xa2dbf279b0e0c6aae3c5e7c174df1d62727370f6e3be021b10f64b1c92269c2f666da0d283fc1c264976ffcbc453a13ca7ed2276b981f514d15df58a78ffa089"]}]}},"extrinsics":["0x280401000b207ef3978901","0x79c3041e00e9021b9689fae32c8bc073379d292b1fbabe530e9b9e1d8ad576a739e9b8735c17579277fa00c552ba91d64c62df9139dcec3c3c70a4c42dc87d6c74857084bc2323375568b1348b5bc99598c8e594b34cfbc752a77adb5a648867ca59ffecdd4f7418f1a06b08066175726120ad8b650800000000056175726101012e101385c27ad02bb7ee0ec65fdf85c0eb3d7d0e100c2e6610f3924516af920a676bf3b61c725181ff28b7f1dd260645f9a4bde5320f1e17dae4c6466c22e481790efd00f7b3b2c91fed2a3dff0d1369790dbd6d88509af84a9dda71b11418738deff844000050003101b456f5a4efb16ffa83d0070000809fea59a750de8af7e66fec197fe84e396fe6c9796293d9f31b329aa7a44224b4e856f5a4efb16ffa83d0070000b42ce8030000d4070000d6070000d8070000db070000dc070000f0070000f2070000f3070000f50700003808000099015c61975d97255ddb070000d00700005501e803000000900100009001000000000000000000018c74408c28f6627f58a8e10b3ec06b98b0166bfb148641a35c5cdfc7a56e68fb00e8764817000000000000000000000000e8764817000000000000000000000099015c8c2de8299067f3070000d00700005501e80300000090010000900100000000000000000001772e98610c34bfcf0dfbdde1794231c18cef8e0d65b360eaa5be668c4c4f3bc700e8764817000000000000000000000000e876481700000000000000000000009d015d01c872d0ebaf85d0070000f50700005501e8030000009001000090010000000000000000000172d8db54e50567185bea9cac281a0c0695e3c6ff79ce1ac0f3123a141a91f23c00e8764817000000000000000000000000e876481700000000000000000000009d015d0452a22bee61fad0070000f20700005501e80300000090010000900100000000000000000001da1b67833da2803322f15d388d8d730d2c043fa44071f883545bb49f574e75dd00e8764817000000000000000000000000e876481700000000000000000000009d015d04d2a15ab51127e8030000d00700005501e8030000009001000090010000000000000000000191ee602c3147cb1245c207502ce63bfc608fb674cbd17dea8ff711c00acb16d600e8764817000000000000000000000000e876481700000000000000000000009d015d057a605f506cfcd4070000d00700005501e80300000090010000900100000000000000000001663406c4106d7204b3ed49303b5a45493ba8939b11248d05a6b700ad690904ff00e8764817000000000000000000000000e876481700000000000000000000009d015d07edc4cbc65e03d0070000d40700005501e80300000090010000900100000000000000000001baf58b8fc9daf3a2e008459ffccd2a1f874ab4d4681e282e7202ae84516f452900e8764817000000000000000000000000e876481700000000000000000000009d015d0a87461a6f93a938080000d00700005501e803000000900100009001000000000000000000012205e84ce99f9186393b37f60be2e7d479c4800b54a0d76b9aead1a0e631676600e8764817000000000000000000000000e876481700000000000000000000009d015d0b652b2ae6ed1ddc070000d00700005501e80300000090010000900100000000000000000001ea09518981c97163dedd6f1867ebce8c10b4085a240e4503e23e0d618d52823600e8764817000000000000000000000000e876481700000000000000000000009d015d0bc334ef110d8af5070000d00700005501e80300000090010000900100000000000000000001baef60381dd8f5b01a7ae04e58e750c8dc1bca679c77350b426d94a84daa41d400e8764817000000000000000000000000e876481700000000000000000000009d015d0be1ee506d55f8d0070000f30700005501e80300000090010000900100000000000000000001b51ac04ad58d0d6f7318e96b6dcd97d43873929680ada3dc7cf3b16e0da607d900e8764817000000000000000000000000e876481700000000000000000000009d015d0c472775baca93f0070000d00700005501e80300000090010000900100000000000000000001fe2a8ab978e14570c1e3d7b84d2b8e74c5a1dc3ad3ad2a804136a32d2ecb660b00e8764817000000000000000000000000e876481700000000000000000000009d015d0fcde7347851edd0070000380800005501e8030000009001000090010000000000000000000110f80573bcf0b8214247ad9997120ab735be98f87146bcf7184dc79081d8391f00e8764817000000000000000000000000e876481700000000000000000000009d015e046fae65527199f2070000d00700005501e8030000009001000090010000000000000000000144a4aa5441aaf968c99c29f2e2c088dc10bd11985a29556d5ac18082f3a82f7400e8764817000000000000000000000000e876481700000000000000000000009d015e1a4e21b9b6ce11d8070000d00700005501e803000000900100009001000000000000000000015063b45fb0f97475aae3195a3a5ee0b06ce909ecc8c856d42d51ebde6fc6773900e8764817000000000000000000000000e876481700000000000000000000009d015e36ad4314650419d0070000f00700005501e8030000009001000090010000000000000000000199b2fad24e2c2bcf925e5d409e5dcf1c62cc94c62da4a99d695a48b5d531c51500e8764817000000000000000000000000e876481700000000000000000000009d015e36c65ca123d5fbd0070000dc0700005501e803000000900100009001000000000000000000014945c417323b5603ca9b397f2d29a1f185227704d9cf6915ba12aa6e0857e98200e8764817000000000000000000000000e87648170000000000000000000000c45e414cb008e0e61e46722aa60abdd672801070bcd12a20ed47eb4280587f3d67bf9bd677081ba99b722fedbed24fbd55dc9d015e4f36708366b722d0070000e80300005501e80300000090010000900100000000000000000001ab66d52587f4cc0ef147f237782d943d64053b83bd057ae3140eb5da113f6cad00e8764817000000000000000000000000e876481700000000000000000000009d015e55c8e02d73966fd6070000d00700005501e80300000090010000900100000000000000000001c0dc79c1cfacfe49d5c0a4f97410fafb445e9a26109716d8902918ce58e8538000e8764817000000000000000000000000e87648170000000000000000000000c85e77dfdb8adb10f78f10a5df8742c545840141347a984a38348904519a9f677ed8009e961dda06cf0842c22dc86cf99bfc3a9d015ea99274c2ff3639d0070000d60700005501e80300000090010000900100000000000000000001a3af9f082277cc0973f9aa7002ca32ff3ba53044cfec8ba674113707082e9e5700e8764817000000000000000000000000e876481700000000000000000000009d015ec412f496dcf830d0070000d80700005501e8030000009001000090010000000000000000000117bd272b0646c5d00cba5dfa84f4bcf40affc6e0901c0e116b3a679aeec62bab00e8764817000000000000000000000000e876481700000000000000000000009d015ec648b30353eed1d0070000db0700005501e80300000090010000900100000000000000000001f548fd93e2ef2ba56672155d27549c6606b3bbcbabb456c71725c4b0b244e2c400e8764817000000000000000000000000e87648170000000000000000000000c45ee678799d3eff024253b90e84927cc680a4c8c86ef2af75c844ea9423f54a1fb92c3c7e6b20ab4c3a1d999503c224a19d3d035f04b49d95320d9021994c850f25b8e385f1020000300000500000aaaa020000001000fbff0000100000000a000000403800005802000000000000000000000000500000c800001e0000000000000000e8764817000000000000000000000000e87648170000000000000000000000e8030000009001001e0000000000000000900100004038000000000000000000000a0000000a0000000a00000001000000010500000001c800000006000000580200000200000059000000000000001e000000280000000102000000140000001501800014803e2629a3f5202d28290e13c9cdb9a5b2bd1948e4b8555391fe5c23307aab315180c89794ff02d4181eff77159b0ec0c3c4881fc329a39e604a1dd235b6e1842d42d48000c0787694c040f5e73d9b7addd6cb603d15d3b0021d9da3ceafbd080d00000401485e4993f016e2d2f8e5f43be7bb2594860400150180010180365975014eb90cb2961e9c770478ee6e346f90ff1f69938faa7594ffd6d2e77380ed544d62efb7b67dbc2b5ee90a5d2cc5b775b866685721bc98a3fc6f6475cde31501800102807333b9790e28aeca8b589386c8eaccea330458c52a6ab8bd39eb77cc01f856e1804e0b297b5ec534c697085672506a8f12657dc2851a729194e82b9a9a20c97a87150180011080ec2e6ab074bc43d699465ee306d3f0a70071543ed241bd7ea99c865d159960898074e7a07c184ddb00d8f5f79daef178513b08af008d2a1733468aa7d48e02225c150180011080ece2ce5e60fe6905c3e6df50113e8d66f98f2bac49959729a762244d906f8cbd800ebe650369ce0e3ce85b22816181f598cc6ecf7a3b22314357ab4181b9ccb867150180040480b3dccee7826596afbcd52862ffd9c7c3d1df14a2b7df16f2f432781b5f358e0d800fe6b03639ff2739e42b263a64b97458bbb7b04a7f13a7dd10b77ba5c3d3940e1d02800464803b021c9ec7daafe981aefb7f480f20fd846f9e6528ca07d46a4139fd98bc925d801093e52db2f352fc46f6bc215527837964bf82b5a6a151e4a9d7c549e0ec0bc880ef3d25ed034c70baa1626c23aff458e551aa9f1215c3e5159cad916fa629d4ea802666a60b7e0791165ae8d8f29e5636b8e3d73ed6c11fdd975859f089ce1c7fba150180080280678785a8785e655a7feae487f9b7751569b8e410633f0a71aa1c1d75547fd9e88090e48c8b881a1711b7c6d3af27d3ea69b50a8de6e34fbd5069798860436a97d9150180080480e6a4e120a54079ae5c308647cef7ddf0c9bcc6d80c8cc46118927b5084d185e780787d5bc4019ae6b7421bbdb3ec47c4fc174606ef1fa0e6cd3984ba3bb78912de990180080c80d066a00dc79b0a8601ea466d09a4c969c246ed7d8b4f029afcd41944e33ae8b080f522d7a1d5ce1ccee6eede035143769201ca120e449e8f64eda7b2dc2a42ba2b80d6a972d738dbf3c6cd7430d3f40c0c035af97f6ff34a543f4dfe596b3aca9ba1dc80082080e089b632e25cbf4a2dcc1323d5eba53b9f6b0ca2d28d527bb7f66cc1e37722a6485ead6eef5c4b1c68eaa71ea17a02d9de0400290180085080720475da1eb4b5f077fca4ad1e6add131c2ce61ab829c8ca4ef18029c79bacc048563524f87eaf5eaf000800001404e8030000485628b8ad2696ed532c0800001404f2070000990180085080de6b2a86ae4215337d8d2b091b03bad41d030bee855474fa9336f1266144151a80aa355c7789c126573837fde95fd60e274cddf219667c77dafaf68056bda3be6680fed053f3246bf831c43bf1220688224a0160521432d33cdb419ac74775f9143c150180100280d41a891824aa749a70b0e27038773a7bbf78a3c4ef1398d0ef7ff58d24a8f5078080ac4fbb91213f5abfbf558bf557d0675e889c6d9e7c795790b2b9f2d5d454f9a1028010178097b598545d7420e0eef7a5606a4b989765b8a6a7544979559907ad255526b1b980e3e173236cbd39a2d737df82d2c6893934705f98c5cbcf8299de49850c0f4bdf80e6949c4c5c09cebe4837df783f910bb5245e849a7813acd7f7f538177a30611980c9f2993961cf92af6b80d4c31d988e48f4b679345d3e751681f4a4c42a2e788480cd365cfd88ca72eac96e334b02cb69ea45e1ec079cf68421a13ad1f62e58751d990180106080c0e3ae6f418b56391e8b43eb63156f27c049c21581fe64e95869db88a428548580130d8ca189ca04528b6c768c16d91748f4e8c4098239bf15ed58ceaaecc7ca64805f738e2d7016159bb83f0acfc05b94f3bfed39826328fbea9a5a6844b0ee9f62150180120080e3b5bf98fc5f0db21bdbcb9438d19e96662671cd4f81a9ee36290c878df4acf5808c0a361cc5e30997a831178a74c430ed562e0885ffee4fa24dddf664876feec42d048018bd801cd402560a1c1ff325789aa57b64069cb2397e3790025023f50710a77035b36d806a589224d4d534b6331ba0977040bc657cd51bf4c05a58067e3d6ac2be3da890801ff5137cda600312402f1b6149d38ef125a161ef8c1f2712d5d553cb6e012e7280c4e9a353ef4519589339594b462d8fef723766373849fcb82b8090be7cac9016803198918edb1541db193c4f4aa6969a32daf26c6b917b261b73550565953172cb80162743d2b05cb83515aead045c17c3cfd247861657fc533d388a'... 15611 more characters
}

```

**Comment by shunjizhan** [comment]
can you clarify:
- how did you start the indexer? (what environment, what command/config)
- did it work before and suddenly stopped working at block `4103773`?

**Comment by shunjizhan** [comment]
@z1z2z3z4z5z6 Feel free to reopen it if it's still an issue for you
