### ISSUE TITLE
evm-subql Indexer fails -- Cannot find module 'http'

### ISSUE THREAD

**Issue by TurtleSnail** [AcalaNetwork/bodhi.js#820]
evm-subql Indexer does not work
```
2023-09-06T23:16:14.297Z <BlockDispatcherService> ERROR failed to index block at height 840000 handleBlock(VMError: Cannot find module 'http'
    at CustomResolver.resolveFull (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:126:9)
    at CustomResolver.resolveFull (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:316:16)
    at CustomResolver.resolve (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:121:15)
    at resolve (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/nodevm.js:317:21)
    at VM2 Wrapper.apply (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/bridge.js:485:11)
    at requireImpl (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:90:19)
    at require (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:171:10)
    at 13685 (/home/acala/bodhi.js/packages/evm-subql/dist/index.js:45620:18)
    at __nccwpck_require__ (/home/acala/bodhi.js/packages/evm-subql/dist/index.js:62506:43)
    at 58936 (/home/acala/bodhi.js/packages/evm-subql/dist/index.js:21754:30)) 
VMError: Cannot find module 'http'
    at CustomResolver.resolveFull (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:126:9)
    at CustomResolver.resolveFull (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:316:16)
    at CustomResolver.resolve (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:121:15)
    at resolve (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/nodevm.js:317:21)
    at VM2 Wrapper.apply (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/bridge.js:485:11)
    at requireImpl (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:90:19)
    at require (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:171:10)
    at 13685 (/home/acala/bodhi.js/packages/evm-subql/dist/index.js:45620:18)
    at __nccwpck_require__ (/home/acala/bodhi.js/packages/evm-subql/dist/index.js:62506:43)
    at 58936 (/home/acala/bodhi.js/packages/evm-subql/dist/index.js:21754:30)
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

VMError: Cannot find module 'http'
    at CustomResolver.resolveFull (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:126:9)
    at CustomResolver.resolveFull (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:316:16)
    at CustomResolver.resolve (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:121:15)
    at resolve (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/nodevm.js:317:21)
    at VM2 Wrapper.apply (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/bridge.js:485:11)
    at requireImpl (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:90:19)
    at require (/home/acala/.nvm/versions/node/v18.12.0/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:171:10)
    at 13685 (/home/acala/bodhi.js/packages/evm-subql/dist/index.js:45620:18)
    at __nccwpck_require__ (/home/acala/bodhi.js/packages/evm-subql/dist/index.js:62506:43)
    at 58936 (/home/acala/bodhi.js/packages/evm-subql/dist/index.js:21754:30) {
  code: 'ENOTFOUND',
  handler: 'handleBlock',
  handlerArgs: '[{"block":{"header":{"parentHash":"0x72d30e730518522f91bdedf81b5a230ab53b4223c0fea3bfdbe4797cc071e9ad","number":840000,"stateRoot":"0x239428026ae516dc1fc28787ac5652163a899f6c9a6ec3694517356dbe2e3582","extrinsicsRoot":"0x0ddae511eb40abc4a616a37bbbaa7c523c595c5bb1015cd513719d8da1284fb7","digest":{"logs":[{"preRuntime":["0x61757261","0x4888320800000000"]},{"seal":["0x61757261","0xba9c257832fb49686309cfcd9f61007208095fa1a77570ffb45dc5377c7a8723f355a61b4700f1c44daf8a3507a0f1deaa22621ef125f95da60fef0d9eb81d8b"]}]}},"extrinsics":["0x280401000b6447b4408001","0xb12a041e00e9024342f3ee63d28353dac9c943f1b049f1973ad10619ea5d39e7d55ad830a30cc9fe4433004257b21d3db2c5ac0f85b8c39b00c52553f7339776369b6c5bd76d427f161ab47882a67e016e9df552dd85d1ce4da1b99c1b53aa73734fdc0fabb4edbcbe56320806617572612047883208000000000561757261010114d34ec1a351b5fbd21d72b4269ba05d23d998915dd93ed4739e4f4b08207861b6adcb5db83bcc1b78579414e2c20b1a9e0a31249deab79952a51a0245f1bd85eeaa9700b8181882d9fda90e945ca8ee8eda6b232ab356eac428d190e4ef961f5909f3b800005000404d0880ffff80b5aa940490413e6135df97515d0fcf89faf1325b9ac0a7fcfa403a40c11aef2480642d751a280c0f4a8562b41a8eedef84bc9510c4b9536d5027ab9a1cc7524f0b80892f03299729ec8ce916e9d1a9e0fee80248d53f63ac1f45db1b07579b516e95804cdba83a15006baca996f2267a6ee82e4183edd09ebaed02a024491d137909bd80a3a75b706fd0efac337846fad34d003c78959b98a5010d40b3600b2d2c066ff9806ffe5a5e9b65d1ee5563e58982df318de364a90d96c932c6171bf49b1510534480f57dc151f256a354d48bf32c6746fbf61d9062eb7aff5df9de33f866cb7532948027df7453387222a1cb6c06ced3f7094ae29a0be11d62ffbf6869c142872a8fa88074854c9e574664c2cf5caf5181a9ed66ff8d2e8ae7fa1d97f90606138adfbd0b800d262cc2a336d6b806cbf0def427d162c57921ca8b7b28f324f83b613ce1a8728052109aaa7b4a2dc25bf751ed07e5a27c082119b844c763eca527d63dfcca80488039ea6065d9592303c5c6ebe5e883a880a6794d370707cf09b08622119fc4adf580ddbab0bb62ee0e3c4a401983eb4a7c9e1ca9911d645a8f90494352649bcb736d80e6a46206f03567b94ec325c8e5b1a10e32d0cd81a69b6de075c100cda537e20d800acb328e7924db50a2dc54a4c8df1f9b3267d6c5225adec0d31686b52559a98b802eb2d99784dd34f695c8569ff32bef6dab6859baac3ce80dbc82349f48bf64cda10280101780cc087090217e4d6d0065105a21a252e75e7fe873baad752fc9dc96c9d6908e46808362c774adcfd52897c31e3997bc39a7fe43b7a98940deb4d32e6fdbed162b8280bf41115c7c29f7d8685792aada115a374d2a18c5786040887997d2eb0586ebde804c1295c38f4019781287ac7db736242b57cd42a1a660ac5526f7ff440f3b258f801367467f31fb236d1fec7fc944164f5cc8a0ecc8d43eb6da487229c0be4fad6651019ef78c98723ddc9073523ef3beefda0c1004805df9a7335700a4cdfcc8be3b2ab627be1242be84590f41348d60ffda9e50559c8047ae0c78097fba48a881fc2f5009945092af2f6bf18cc0e93ec7417afde165b91d028004648099331411b932cd55fd08bfa75fa5001c0b6070cc64b606126c3a656b6f6d17ea804c3523ddd8f20cec8908d106ca250af7bc1c5523f885874ed76b3e7c82e6b8ad80c70085088ee7dbf456defa51128ed54dc74e96007d09e392bf4de6fad9648884808ad0e6f6804c1a9f66866c2d664243dea4186f4ebe0711efdd5e8f0112a56855887e207f03cfdce586301014700e2c2593eec2d17a76153ff51817f12d9cfc3c7f04007d059eb6f36e027abb2091cfb5110ab5087ff96e685f06155b3cd9a8c9e5e9a23fd5dc13a5ed209110651000000000685f08316cbf8fa0da822a20ac1c55bf1be3203b10000000000000505f0e7b9012096b41c4eb3aaf947f6ea42908000080e619cbe3c1fec0aaa9fb73df3605b3bec140c00d30b6707243392b99ef1e130d80f9308f091f100659446bc94c5332bd7a8ed442723ae55144e27ff7646b5bbad680b98cb83f8fb770371616f39b07a02b1c087eca59b38ce691c2bb978de3caff60800d49fef039517cc312c00412803ca1df50ac6d90c50541f649a9c85b83c0fdd880fb1cd752492075387cbbc0a273ab9775b37c422f2c4b18fbcdf304da3b18d43f8017e9e016b84b7d258c037008ff3bd0344196b3dac5e57c86035e1ce97de996d580c5cefcf79baea7f73fdd830e200d6884b2b76a353d0127c7f7f413dc6ade3fec685f090e2fbf2d792cb324bffa9427fe1f0e20b198970010a2970085049e710b30bd2eab0352ddcc26417aa1944fc3808c20628adeae774ff82fd3197e9205ab079321091cac903835749114000e17f98012b7144c627a8349cf685883d4a16304a591205190c5d5d9659b9acc8fa62503804be7eac274dfc00ae1c1c1321a82c5921d2a59f484e451dfa79db3fca6481d3b80246aee256dca1772baf4cc06c1e497c797cbebcf4ee0cb864c61e899b1ed49894c5f03c716fb8fff3de61a883bb76adb34a204008056af5e5cc44a02f20b650a5d1aec0b1caecbe75ef8de219b6db0683131aa3f894c5f0f4993f016e2d2f8e5f43be7bb259486040080cd9207c27d0f6207630d541e51f900b0eff169826bede00f8af1ec52f0ff4887807ed834920608af45773ed0314ee4e90af9dc16a78fdbd899f4072d7f16c8253b71019ede3d8a54d27e44a9d5ce189618f22d3008505f0e7b9012096b41c4eb3aaf947f6ea4290802004c5f03b4123b2e186e07fb7bad5dda5f55c0040080043ce1c633b4b41165606b336bf2486f1f7ce386d0a57b37ce03ae2c93f6c51bdc800820808d8d733e3ace6462788cfb3cba802086d5a2f413117d126063a12d409c31d08f485ead6eef5c4b1c68eaa71ea17a02d9de0400150180080480da3af855e412d0c494521a4c31e7cdd3a6f9b3a1fdcf036da89304f2abffe8dd8005ecb8ae8303ac69b008c1381561bb5e6e13d47d5e98b736e6d9c07502d24f3e150180400880a8d4e22d1170a98354ddcef91d89363a1d22e4c3ee31f081455efb1b8aec25a3808c68f773671aec1db46b2c37b4c827e64aa7290d65e305cdaaa6b175596256f179035f04b49d95320d9021994c850f25b8e3852d030000a000005000000a00000000c8000000c800000a0000000a00000040380000580200000000500000c8000000e87648170000000a0000000000000000c0d3cf8eb70000000000000000000000c0d3cf8eb700000000000000000000e8030000009001000a00000000000000009001004038000000000000000000000a0000000a0000000a00000001000000010500000001c8000000060000005802000002000000580200000200000059000000000000001e0000002800000000c817a804000000000200000014000000f8770d7fefc408aac59dbfe80a72ac8e3ce5b6ff6f7d467b87a9e803000080a5f80dd2f860b391a779dad8f9d2d4fdff9b0c85c05749c34e13e045df45726e1d02806500805bc789deb87860c8cc0ce8c50924fc68e5da449ac5a1a6dbba417594bb09a91d802d1232f73656c81a879411beaa33e2074b2da2e05b57b0866f8230b35b8df4fa809f284a86f45e0802b1d3be101948799c566e6927487026cf11fa7b27c5ed045d80af579d5ddc5c697d42bfc014076594e66c7b324cfd3017810c4e93e4f6f0ae9ea1019d0da05ca59913bc38a8630590f2627c054080b82534c6e3302cb438b34048cf39e5d8f7e96749f54ce0f5d716c6db0fe924bd4c5f0a351b6a99a5b21324516e668bb86a57040080560e60e67e5d4f44cc10c5d2dff22213eddfb1e8c1410ff57d3788186f1f26ed1501800110809fd8f93888423bee98ee24be33afea554ff61d0b9055db81041477acef6561ef8054c3a0f845ec2536d8cb9dd15c0f839487edc1de3cd6093043597e0dc15cd2870000"]},"justifications":null}]'
}

Node.js v18.12.0
```

**Comment by shunjizhan** [comment]
how did you start the evm-subql?

below docker compose worked for me
```
services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  subquery-node:
    image: acala/evm-subql:2.7.7
    container_name: subquery-node
    ports:
      - 3000:3000
    depends_on:
      - postgres
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: host.docker.internal
      DB_PORT: 5432
    command:
      - -f=./project-acala-840000.yaml
      - --network-endpoint=wss://acala-rpc.aca-api.network
      - --db-schema=acala_evm
      - --log-level=debug
      - --unsafe
      - --disable-historical
```

**Comment by shunjizhan** [comment]
you might forget to add `--unsafe` flag?

**Comment by shunjizhan** [comment]
@TurtleSnail gonna close this, but feel free to re-open it if you are still facing any issue
