### ISSUE TITLE
subql-node fails

### ISSUE THREAD

**Issue by TurtleSnail** [AcalaNetwork/bodhi.js#960]
What does it mean?
```
$ DB_USER=postgres DB_PASS=passowrd DB_DATABASE=acala DB_HOST=localhost DB_PORT=5432 yarn index 
2024-03-02T13:42:19.272Z <subql-node> INFO Current @subql/node version is 1.21.2 
2024-03-02T13:42:19.272Z <subql-node> WARN UNSAFE MODE IS ENABLED. This is not recommended for most projects and will not be supported by our hosted service 
2024-03-02T13:42:19.466Z <indexer> INFO indexer manager start 
2024-03-02T13:42:19.661Z <store> INFO Historical state is disabled 
2024-03-02 13:42:19        RPC-CORE: getRuntimeVersion(at?: BlockHash): RuntimeVersion:: -32000: Client error: Api called for an unknown Block: State already discarded for 0xfc41b9bd8ef8fe53d58c7ea67c794c7ec9a73daf05e6d54b14ff6342c99ba64c
2024-03-02 13:42:19        RPC-CORE: getHeader(hash?: BlockHash): Header:: -32000: Client error: Api called for an unknown Block: State already discarded for 0xfc41b9bd8ef8fe53d58c7ea67c794c7ec9a73daf05e6d54b14ff6342c99ba64c
2024-03-02T13:42:19.700Z <subql-node> ERROR Node failed to start 
RpcError: -32000: Client error: Api called for an unknown Block: State already discarded for 0xfc41b9bd8ef8fe53d58c7ea67c794c7ec9a73daf05e6d54b14ff6342c99ba64c
    at checkError (/home/acala/.nvm/versions/node/v20.11.1/lib/node_modules/@subql/node/node_modules/@polkadot/rpc-provider/cjs/coder/index.js:24:15)
    at RpcCoder.decodeResponse (/home/acala/.nvm/versions/node/v20.11.1/lib/node_modules/@subql/node/node_modules/@polkadot/rpc-provider/cjs/coder/index.js:42:9)
    at WsProvider.<anonymous> (/home/acala/.nvm/versions/node/v20.11.1/lib/node_modules/@subql/node/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:145:93)
    at WebSocket.<anonymous> (/home/acala/.nvm/versions/node/v20.11.1/lib/node_modules/@subql/node/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:134:96)
    at callListener (/home/acala/.nvm/versions/node/v20.11.1/lib/node_modules/@subql/node/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/home/acala/.nvm/versions/node/v20.11.1/lib/node_modules/@subql/node/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:518:28)
    at Receiver.receiverOnMessage (/home/acala/.nvm/versions/node/v20.11.1/lib/node_modules/@subql/node/node_modules/ws/lib/websocket.js:1209:20)
    at Receiver.emit (node:events:518:28)
    at /home/acala/.nvm/versions/node/v20.11.1/lib/node_modules/@subql/node/node_modules/ws/lib/receiver.js:608:16
```

**Comment by xlc** [comment]
the rpc node it connects to is not an archive node and it is unable to access historical state
