### ISSUE TITLE
Failed to get tx receipt

### ISSUE THREAD

**Issue by zjb0807** [AcalaNetwork/bodhi.js#961]
```
curl --location 'https://eth-rpc-acala.aca-api.network' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "method": "eth_getTransactionReceipt",
    "params": [
        "0x7fe92ec600f15cd25253b421bc151c51b0276b7d"
    ],
    "id": 1
}'
```

```
{
  "id": 1,
  "jsonrpc": "2.0",
  "error": {
    "code": -32602,
    "message": "invalid argument 0: hex string has length 40 but want 64"
  }
}
```

**Comment by zjb0807** [comment]
My bad, the error message was
```
curl --location 'https://eth-rpc-acala.aca-api.network' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "method": "eth_getTransactionReceipt",
    "params": [
        "0x5ec485421be298a4a2535ed03c8e46a43b85a324fe2aca8cf6c603adbd7504d3"
    ],
    "id": 1
}'
```

```
{
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "to": "0x7fe92ec600f15cd25253b421bc151c51b0276b7d",
        "from": "0xdf9db854a5305632bbb380134597cd44c0826ab8",
        "contractAddress": null,
        "transactionIndex": "0x0",
        "gasUsed": "0xdb218",
        "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "blockHash": "0x8bc0676c77df474cb18007adbae190c49f50e072345cdf255b65558987cea03f",
        "transactionHash": "0x5ec485421be298a4a2535ed03c8e46a43b85a324fe2aca8cf6c603adbd7504d3",
        "logs": [],
        "blockNumber": "0x57b581",
        "cumulativeGasUsed": "0x0",
        "effectiveGasPrice": "0xcdde1de1",
        "status": "0x0",
        "type": "0x0",
        "exitReason": "{\"revert\":\"Reverted\"}"
    }
}
```


blockscout conversion failed on `exitReason`
```
2024-03-14T01:04:27.083 [error] Task #PID<0.19909.4415> started from #PID<0.19738.4415> terminating
** (ArgumentError) Could not convert receipt to elixir

Receipt:
  %{"blockHash" => "0x8bc0676c77df474cb18007adbae190c49f50e072345cdf255b65558987cea03f", "blockNumber" => "0x57b581", "contractAddress" => nil, "cumulativeGasUsed" => "0x0", "effectiveGasPrice" => "0xcdde1de1", "exitReason" => "{\"revert\
":\"Reverted\"}", "from" => "0xdf9db854a5305632bbb380134597cd44c0826ab8", "gas" => 803409, "gasUsed" => "0xdb218", "logs" => [], "logsBloom" => "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "status" => "0x0", "to" => "0x7fe92ec600f15cd25253b4
21bc151c51b0276b7d", "transactionHash" => "0x5ec485421be298a4a2535ed03c8e46a43b85a324fe2aca8cf6c603adbd7504d3", "transactionIndex" => "0x0", "type" => "0x0"}

Errors:
  {:unknown_key, %{key: "exitReason", value: "{\"revert\":\"Reverted\"}"}}

    (ethereum_jsonrpc 5.3.0) lib/ethereum_jsonrpc/receipt.ex:236: EthereumJSONRPC.Receipt.ok!/2
    (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 5.3.0) lib/ethereum_jsonrpc/receipts.ex:138: EthereumJSONRPC.Receipts.fetch/2
    (elixir 1.14.5) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.5) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
```

**Comment by zjb0807** [comment]
We should delete this field. Implement [debug_traceTransaction](https://github.com/AcalaNetwork/bodhi.js/issues/289) to achieve this. blockscout also displays error messages through this RPC.
